# -*- mode: python -*-

Import('env')
Import("get_option")

env = env.Clone()

env.Library(
    target='document_source_bson_input',
    source=[
        'document_source_bson_file.cpp',
        'document_source_stdin.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/pipeline/pipeline',
    ],
)

env.Program(
    target="mqlrun",
    source=[
        "mqlrun.cpp",
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/auth/authmocks',
        '$BUILD_DIR/mongo/db/exec/working_set',
        '$BUILD_DIR/mongo/db/index/index_access_methods',
        '$BUILD_DIR/mongo/db/query_exec',
        'document_source_bson_input',
    ],
    AIB_COMPONENT='mh',
    AIB_COMPONENTS_EXTRA=[
        'dist-test',
    ],
)
