# -*- mode: python -*-

Import('env')

env = env.Clone()

env.InjectThirdParty(libraries=['librdkafka'])

env.CppUnitTest(
    target='streams_kafka_source_test',
    source=[
        'kafka_source_test.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/third_party/librdkafka/rdkafka',
        '$BUILD_DIR/third_party/librdkafka/rdkafka++',
    ],
)
