# -*- mode: python -*-

Import("env")

env = env.Clone()

env.Library(
    target="report_tool",
    source=[
        "report.cpp",
    ],
    LIBDEPS_PRIVATE=[
        "$BUILD_DIR/mongo/base",
        "$BUILD_DIR/mongo/util/quick_exit",
    ]
)
