# -*- mode: python -*-

Import("env")

env = env.Clone()

env.Library(
    target="report_tool",
    source=[
        "report.cpp",
    ],
    LIBDEPS_PRIVATE=[
        "$BUILD_DIR/mongo/base",
    ]
)

env.Library(
    target="gssapi_helpers",
    source=[
        "gssapi_helpers.cpp"
    ],
    LIBDEPS_PRIVATE=[
        "$BUILD_DIR/mongo/base",
    ],
    SYSLIBDEPS=[
        'gssapi_krb5',
    ],
)
