# -*- mode: python -*-

Import("env")

env = env.Clone()

env.Library(
    target="report_tool",
    source=[
        "report.cpp",
    ],
    LIBDEPS_PRIVATE=[
        "$BUILD_DIR/mongo/base",
    ],
)

env.Library(
    target="core_options_stub",
    source=[
        "core_options_stub.cpp",
    ],
    LIBDEPS_PRIVATE=[
        "$BUILD_DIR/mongo/base",
    ],
)
