# -*- mode: python -*-

Import("env")

env.Library(target='look_up',
            source=['document_source_look_up.cpp',
            ],
            LIBDEPS=['$BUILD_DIR/mongo/base',
                     '$BUILD_DIR/mongo/db/pipeline/document_source',
                    ],
            LIBDEPS_DEPENDENTS=['$BUILD_DIR/mongo/db/commands/core'])

env.CppUnitTest(target='enterprise_pipeline_test',
                source='enterprise_pipeline_test.cpp',
                LIBDEPS=['look_up',
                         '$BUILD_DIR/mongo/db/auth/authorization_manager_mock_init',
                         '$BUILD_DIR/mongo/db/pipeline/pipeline',
                         '$BUILD_DIR/mongo/db/service_context',
                        ],)
