# -*- mode: python -*-

Import('env')

env = env.Clone()

env.InjectThirdParty(libraries=['librdkafka'])
env.SConscript(dirs=['tests'], exports=['env'])

env.Library(
    target='streams_management',
    source=[
        'stream_manager.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
        '../commands/streams_ops_idl',
        '../exec/streams_operators',
        '../exec/streams_parser',
    ],
)
