# -*- mode: python -*-

Import('env')

env = env.Clone()

env.Library(
    target='stream_management',
    source=[
        'stream_manager.cpp',
    ],
    LIBDEPS=['$BUILD_DIR/mongo/base'],
)

env.CppUnitTest(
    target='stream_manager_unit_test',
    source=[
        'stream_manager_test.cpp',
    ],
    LIBDEPS=['$BUILD_DIR/mongo/base', 'stream_management'],
)
