# -*- mode: python -*-

Import('env')

env = env.Clone()

env.SConscript(dirs=['tests'], exports=['env'])

env.Library(
    target='streams_util',
    source=[
        'metric_manager.cpp',
        'metrics.cpp',
        'exception.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
    ],
)
