#
# Copyright (C) 2018 MongoDB, Inc.  All Rights Reserved.
#

global:
  cpp_namespace: "mongo"

imports:
  - "mongo/db/basic_types.idl"

server_parameters:
  ldapUseConnectionPool:
    description: "Whether to use connection pooling for LDAP connections"
    default: true
    set_at: startup
    cpp_vartype: bool
    cpp_varname: ldapUseConnectionPool
    redact: false

  ldapConnectionPoolUseLatencyForHostPriority:
    description: >
        Whether the LDAP connection pool should track and use latency when deciding the order
        of LDAP hosts to connect to
    default: true
    set_at: startup
    cpp_vartype: bool
    cpp_varname: ldapConnectionPoolUseLatencyForHostPriority
    redact: false

  ldapConnectionPoolMinimumConnectionsPerHost:
    description: >
        The number of connections to keep open to each LDAP host
    default: 1
    set_at: startup
    cpp_vartype: int
    cpp_varname: ldapConnectionPoolMinimumConnectionsPerHost
    redact: false

  ldapConnectionPoolMaximumConnectionsPerHost:
    description: >
        The maximum number of connections to keep open to each LDAP host
    default:
      expr: std::numeric_limits<int>::max()
    set_at: startup
    cpp_vartype: int
    cpp_varname: ldapConnectionPoolMaximumConnectionsPerHost
    redact: false

  ldapConnectionPoolMaximumConnectionsInProgressPerHost:
    description: >
        The maximum number of in-progress connect operations (to prevent connection storms)
    default: 2
    set_at: startup
    cpp_vartype: int
    cpp_varname: ldapConnectionPoolMaximumConnectionsInProgressPerHost
    redact: false

  ldapConnectionPoolHostRefreshIntervalMillis:
    description: >
        The amount of time (in milliseconds) between checking the health of pooled LDAP connections
    default: 60000
    set_at: startup
    cpp_vartype: int
    cpp_varname: ldapConnectionPoolRefreshInterval
    redact: false

  ldapConnectionPoolIdleHostTimeoutSecs:
    description: >
        The amount of time (in seconds) after there are no requests to an LDAP server to keep
        pooled connections open to it.
    default: 300
    set_at: startup
    cpp_vartype: int
    cpp_varname: ldapConnectionPoolIdleHostTimeoutSecs
    redact: false

  ldapForceMultiThreadMode:
    description: >
        MongoDB detects if OpenLDAP is not thread safe unless this flag is set.
    default: false
    set_at: startup
    cpp_vartype: bool
    cpp_varname: ldapForceMultiThreadMode
    condition:
      preprocessor: '!defined(_WIN32)'
    redact: false

  ldapAbortOnNameMappingFailure:
    description: >
        Abort user to DN mapping transformation if the LDAP server returns an error.
    default: true
    set_at: startup
    cpp_vartype: bool
    cpp_varname: ldapAbortOnNameMappingFailure
    redact: false

  ldapEnableOpenLDAPLogging:
    description: >
        Enable trace-level OpenLDAP logging embedded within standard server logs.
    default: false
    set_at: startup
    cpp_vartype: bool
    cpp_varname: ldapEnableOpenLDAPLogging
    condition:
      preprocessor: '!defined(_WIN32)'
    redact: false
