# -*- mode: python -*-

Import(["env"])

env = env.Clone()

if not env.TargetOSIs("darwin"):
    env.CppUnitTest(
        target="enterprise_ldap_test",
        source=[],
        LIBDEPS=[],
    )

env.BazelProgram(
    target="mongoldap",
    source=[],
    AIB_COMPONENT="mongoldap",
    AIB_COMPONENTS_EXTRA=[
        "dist",
        "dist-test",
        "tools",
    ],
)
