# -*- mode: python -*-

Import(["env"])

env = env.Clone()

if not env.TargetOSIs("darwin"):
    env.CppUnitTest(
        target="enterprise_ldap_test",
        source=[],
        LIBDEPS=[],
    )

env.Program(
    target="mongoldap",
    source=[
        "ldap_tool.cpp",
        "ldap_tool_options.cpp",
        "ldap_tool_options_gen.cpp",
    ]
    + env.WindowsResourceFile("ldap_tool.rc"),
    AIB_COMPONENT="mongoldap",
    AIB_COMPONENTS_EXTRA=[
        "dist",
        "dist-test",
        "tools",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/base",
        "$BUILD_DIR/mongo/base/secure_allocator",
        "$BUILD_DIR/mongo/client/native_sasl_client",
        "$BUILD_DIR/mongo/db/log_process_details",
        "$BUILD_DIR/mongo/db/service_context_non_d",
        "$BUILD_DIR/mongo/util/dns_query",
        "$BUILD_DIR/mongo/util/net/http_client_impl",
        "$BUILD_DIR/mongo/util/options_parser/options_parser_init",
        "$BUILD_DIR/mongo/util/signal_handlers",
        "$BUILD_DIR/mongo/util/version_impl",
        "../util/report_tool",
        "ldap_manager",
        "ldap_manager_impl",
        "ldap_options_mongod",
        "ldap_query",
    ],
)
