# Copyright (C) 2021-present MongoDB, Inc. and subject to applicable commercial license.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the Server Side Public License, version 1,
# as published by MongoDB, Inc.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Server Side Public License for more details.
#
# You should have received a copy of the Server Side Public License
# along with this program. If not, see
# <http://www.mongodb.com/licensing/server-side-public-license>.
#
# As a special exception, the copyright holders give permission to link the
# code of portions of this program with the OpenSSL library under certain
# conditions as described in each individual source file and distribute
# linked combinations including the program with the OpenSSL library. You
# must comply with the Server Side Public License in all respects for
# all of the code used other than as permitted herein. If you modify file(s)
# with this exception, you may extend this exception to your version of the
# file(s), but you are not obligated to do so. If you do not wish to do so,
# delete this exception statement from your version. If you delete this
# exception statement from all source files in the program, then also delete
# it in the license file.
#

global:
    cpp_namespace: "mongo::audit"

imports:
    - "mongo/db/basic_types.idl"
    - "audit/audit_config.idl"

commands:
    getAuditConfig:
        description: "Returns the current audit configuration"
        command_name: getAuditConfig
        cpp_name: GetAuditConfigCommand
        namespace: ignored
        api_version: ""
        strict: false
        reply_type: AuditConfigDocument
        fields: {}

    setAuditConfig:
        description: "Update the runtime audit configuration"
        command_name: setAuditConfig
        cpp_name: SetAuditConfigCommand
        namespace: ignored
        api_version: ""
        strict: false
        fields:
            filter: object
            auditAuthorizationSuccess: bool

    logApplicationMessage:
        description: "Emit a custom message to the audit log"
        api_version: ""
        command_name: logApplicationMessage
        namespace: type
        type: string
        cpp_name: LogApplicationMessageCommand
        reply_type: OkReply
        strict: false
