# Copyright (C) 2019-present MongoDB, Inc. and subject to applicable commercial license.

global:
    cpp_namespace: "mongo::audit"
    cpp_includes:
        - "audit/audit_options.h"
        - "mongo/db/server_feature_flags_gen.h"
    configs:
        section: 'Auditing Options'
        source: [ cli, ini, yaml ]

server_parameters:
    auditAuthorizationSuccess:
        description: 'Enable to audit when authentication succeeds'
        set_at: [ startup, runtime ]
        default: false
        cpp_class:
            name: AuditAuthorizationSuccessSetParameter
            override_set: true
        redact: false

    auditConfig:
        description: 'Stores the audit configuration'
        set_at: cluster
        cpp_class:
            name: AuditConfigParameter
            override_set: true
            override_validate: true
        redact: false
        omit_in_ftdc: false

configs:
    "auditLog.destination":
        description: 'Destination of audit log output. (console/syslog/file)'
        short_name: auditDestination
        arg_vartype: String
        validator:
            callback: validateAuditLogDestination
    "auditLog.format":
        description: 'Format of the audit log, if logging to a file. (BSON/JSON)'
        short_name: auditFormat
        arg_vartype: String
        requires: 'auditLog.destination'
        validator:
            callback: validateAuditLogFormat
    "auditLog.path":
        description: 'Full filespec for audit log file'
        short_name: auditPath
        arg_vartype: String
        requires: 'auditLog.destination'
    "auditLog.runtimeConfiguration":
        description: "Configure audit filter and auditAuthorizationSuccess via commands"
        short_name: auditRuntimeConfiguration
        arg_vartype: Bool
        requires: 'auditLog.destination'
    "auditLog.filter":
        description: 'Filter spec to screen audit records'
        short_name: auditFilter
        arg_vartype: String
        requires: 'auditLog.destination'
    "auditLog.compressionMode":
        description: 'Mode to be used for compressing the audit log'
        short_name: auditCompressionMode
        arg_vartype: String
        requires: 'auditLog.destination'
    "auditLog.localAuditKeyFile":
        description: 'File path of the audit log encryption key file'
        short_name: auditLocalKeyFile
        arg_vartype: String
        requires: 'auditLog.destination'
        conflicts: 'auditLog.auditEncryptionKeyIdentifier'
    "auditLog.auditEncryptionKeyIdentifier":
        description: 'UID of the KMIP key to be used for audit log encryption'
        short_name: auditEncryptionKeyUID
        arg_vartype: String
        requires: ['security.kmip.serverName', 'auditLog.destination']
        conflicts: 'auditLog.localAuditKeyFile'
    "auditLog.schema":
        description: Event schema to use in audit log output
        short_name: auditSchema
        arg_vartype: String
        requires: 'auditLog.destination'
        validator:
            callback: validateAuditLogSchema