# Copyright (C) 2021-present MongoDB, Inc. and subject to applicable commercial license.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the Server Side Public License, version 1,
# as published by MongoDB, Inc.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Server Side Public License for more details.
#
# You should have received a copy of the Server Side Public License
# along with this program. If not, see
# <http://www.mongodb.com/licensing/server-side-public-license>.
#
# As a special exception, the copyright holders give permission to link the
# code of portions of this program with the OpenSSL library under certain
# conditions as described in each individual source file and distribute
# linked combinations including the program with the OpenSSL library. You
# must comply with the Server Side Public License in all respects for
# all of the code used other than as permitted herein. If you modify file(s)
# with this exception, you may extend this exception to your version of the
# file(s), but you are not obligated to do so. If you do not wish to do so,
# delete this exception statement from your version. If you delete this
# exception statement from all source files in the program, then also delete
# it in the license file.
#

global:
    cpp_namespace: "mongo::audit"

imports:
    - "mongo/db/basic_types.idl"

server_parameters:
    auditConfigPollingFrequencySecs:
        description: 'How often should mongos or non-config monogd nodes query audit config'
        set_at: startup
        default: 300
        cpp_varname: gAuditConfigPollingFrequencySecs
        cpp_vartype: int
        validator: { gt: 0 }
        redact: false

    auditEncryptionHeaderMetadataFile:
        description: 'File name to use for logging audit headers in addition to logging them in the audit log file'
        set_at: startup
        default: ""
        cpp_varname: 'gAuditEncryptionHeaderMetadataFile'
        cpp_vartype: 'std::string'
        redact: false

    auditEncryptKeyWithKMIPGet:
        description: 'Use KMIP Get request to retrieve the key encryption key for encrypting the audit log encryption key'
        set_at: startup
        cpp_varname: gAuditEncryptKeyWithKMIPGet
        cpp_vartype: bool
        default: false
        redact: false

    auditEncryptionWithKMS:
        description: 'Cloud only feature'
        set_at: startup
        cpp_varname: gAuditEncryptionWithKMS
        cpp_vartype: bool
        default: false
        redact: false

structs:
    AuditConfigDocument:
        description: "On-disk representation of runtime audit configuration"
        strict: false
        fields:
            _id:
                # Always 'audit' for this document.
                # optional to allow us to use this for parsing on-disk documents,
                # but still allow us to exclude it for serializing in replies
                type: string
                optional: true
            filter: object_owned
            auditAuthorizationSuccess: bool
            clusterParameterTime: logicalTime
