# -*- mode: python; -*-


Import("env")

env = env.Clone()

env.InjectThirdParty(libraries=["asio"])

env.BazelProgram(
    target="mongoauditdecrypt",
    source=[],
    AIB_COMPONENT="mongoauditdecrypt",
    AIB_COMPONENTS_EXTRA=[
        "dist-test",
    ],
)

env.CppUnitTest(
    target="audit_test",
    source=[],
    LIBDEPS=[],
)

# writes multi-byte sequences to console
# to support manual testing of console stream under Windows
# output should be visually verified under Command Prompt or Power Shell
env.BazelProgram(
    target="console_test",
    source=[],
    AIB_COMPONENT="standalone-console-test",
)

env.Benchmark(
    target="audit_bm",
    source=[
        "audit_bm.cpp",
        "audit_bm_fixture.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/db/audit",
        "$BUILD_DIR/mongo/db/auth/authmocks",
        "$BUILD_DIR/mongo/transport/transport_layer_mock",
        "$BUILD_DIR/mongo/unittest/unittest",
        "audit_enterprise",
    ],
)
