#
# Copyright (C) 2019-present MongoDB, Inc. and subject to applicable commercial license.
#

global:
    cpp_namespace: "mongo"

imports:
    - "mongo/db/basic_types.idl"

structs:
    KeystoreMetadataFileData:
        description: "Metadata file for the encrypted storage engine keystore"
        fields:
            version:
                description: "Schema version of the keystore"
                type: int
            dirty:
                description: "Whether the keystore is dirty and requires a key rollover"
                type: bool
                default: false
