#
# Copyright (C) 2019 MongoDB, Inc.  All Rights Reserved.
#

global:
    cpp_namespace: "mongo"

imports:
    - "mongo/idl/basic_types.idl"

structs:
    KeystoreMetadataFileData:
        description: "Metadata file for the encrypted storage engine keystore"
        fields:
            version:
                description: "Schema version of the keystore"
                type: int
            dirty:
                description: "Whether the keystore is dirty and requires a key rollover"
                type: bool
                default: false
