# Copyright (C) 2019-present MongoDB, Inc.

global:
    cpp_namespace: "mongo"
    cpp_includes:
        - "mongo/config.h"
    configs:
        section: 'Encryption at rest options'
        source: [ cli, ini, yaml ]

configs:
    "security.kmip.keyIdentifier":
        description: 'KMIP unique identifier for existing key to use'
        short_name: kmipKeyIdentifier
        arg_vartype: String
    "security.kmip.serverName":
        description: 'KMIP server host name'
        short_name: kmipServerName
        arg_vartype: String
    "security.kmip.port":
        description: 'KMIP server port (defaults to 5696)'
        short_name: kmipPort
        arg_vartype: Int
        requires: "security.kmip.serverName"
    "security.kmip.clientCertificateFile":
        description: 'Client certificate for authenticating to KMIP server'
        short_name: kmipClientCertificateFile
        arg_vartype: String
        requires: "security.kmip.serverName"
    "security.kmip.clientCertificatePassword":
        description: 'Client certificate for authenticating Mongo to KMIP server'
        short_name: kmipClientCertificatePassword
        arg_vartype: String
        redact: true
        requires: "security.kmip.clientCertificateFile"
    "security.kmip.serverCAFile":
        description: 'CA File for validating connection to KMIP server'
        short_name: kmipServerCAFile
        arg_vartype: String
    "security.kmip.clientCertificateSelector":
        description: 'Client Certificate in system store for authenticating to KMIP server'
        short_name: kmipClientCertificateSelector
        arg_vartype: String
        conflicts:
            - "security.kmip.clientCertificateFile"
            - "security.kmip.clientCertificatePassword"
        condition:
            preprocessor: 'defined(MONGO_CONFIG_SSL_CERTIFICATE_SELECTORS)'

