#
# Copyright (C) 2018 MongoDB, Inc.  All Rights Reserved.
#

global:
    cpp_namespace: "mongo"

configs:
    security.redactClientLogData:
        short_name: redactClientLogData
        description: "Redact client data written to the diagnostics log"
        source: [ cli, ini, yaml ]
        arg_vartype: Switch

server_parameters:
    redactClientLogData:
        description: "Whether or not to perform redaction in client logs"
        set_at: runtime
        cpp_class:
            name: RedactClientLogDataSetting
            override_set: true
        redact: false
