Import("env")

env.Library(
    target='queryable_datafile',
    source=[
        'queryable_alloc_state.cpp',
        'queryable_datafile.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/concurrency/write_conflict_exception',
        '../blockstore/blockstore',
    ],
)

env.Library(
    target='queryable_mmapv1_fs_helpers',
    source=[
        'queryable_mmap_v1_fs_helpers.cpp',
    ],
)

env.Library(
    target='queryable_mmapv1',
    source=[
        'queryable_evictor.cpp',
        'queryable_global_options.cpp',
        'queryable_mmap_v1_extent_manager.cpp',
        'queryable_mmap_v1_init.cpp',
    ],
    LIBDEPS_DEPENDENTS=[
        '$BUILD_DIR/mongo/db/serveronly',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/storage/mmap_v1/mmap',
        '../blockstore/blockstore',
        'queryable_datafile',
        'queryable_mmapv1_fs_helpers',
    ],
    LIBDEPS_TAGS=[
        # Depends on symbols defined in serverOnlyfiles
        'incomplete',
    ],
)

env.CppIntegrationTest(
    target='queryable_mmapv1_fs_helpers_test',
    source=[
        'queryable_mmap_v1_fs_helpers_test.cpp',
    ],
    LIBDEPS=[
        'queryable_mmapv1_fs_helpers',
    ],
)

env.CppIntegrationTest(
    target='datafile_integration_test',
    source=[
        'blockstore_extent_manager_test.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/util/processinfo',
        'queryable_datafile',
    ],
)
