# -*- mode: python -*-

Import("env")

env = env.Clone()

dirs = ["commands", "exec", "management", "tools", "third_party", "util"]

# TODO(SERVER-74961): add something like InjectStreamsThirdParty('mongocxx') to make this easier.
env["MONGOCXX_DIR"] = "$BUILD_DIR/mongo/db/modules/enterprise/src/streams/third_party/mongocxx/dist"

env.SConscript(dirs=dirs, exports=["env"])
