#
# Copyright (C) 2019 MongoDB, Inc.  All Rights Reserved.
#

global:
    cpp_namespace: "mongo"

imports:
    - "mongo/idl/basic_types.idl"

enums:
    KMSProvider:
        description: "Enumeration of supported KMS Providers"
        type: string
        values:
            aws: "aws"
            local: "local"

structs:
    # Options passed to Mongo() javascript constructor
    awsKMS:
        description: "AWS KMS config"
        fields:
          accessKeyId: string
          secretAccessKey: string
          sessionToken:
            type: string
            optional: true
          url:
            type: string
            optional: true

    # Options passed to Mongo() javascript constructor
    localKMS:
        description: "Local KMS config"
        fields:
          key: bindata_generic

    kmsProviders:
      description: "Supported KMS Providers"
      strict: true
      fields:
        aws:
          type: awsKMS
          optional: true
        local:
          type: localKMS
          optional: true

    clientSideFLEOptions:
        description: "FLE Options inputted through the Mongo constructor in the shell"
        fields:
          keyVaultCollection: #Parsed as a JSHandleValue, not through IDL
            type: void
            ignore: true
          kmsProviders: kmsProviders
          useRemoteSchemas:
            type: bool
            optional: true
          schemas:
            type: object
            optional: true

    awsEncryptResponse:
        description: "Response from AWS KMS Encrypt request, i.e. TrentService.Encrypt"
        fields:
          CiphertextBlob:
            type: string
          KeyId:
            type: string

    awsDecryptResponse:
        description: "Response from AWS KMS Decrypt request, i.e. TrentService.Decrypt"
        fields:
          Plaintext:
            type: string
          KeyId:
            type: string

    awsMasterKey:
        description: "AWS KMS Key Store Description"
        fields:
          provider:
            type: string
            default: '"aws"'
          key:
            type: string
          region:
            type: string
          endpoint:
            type: string

    awsMasterKeyAndMaterial:
        description: "AWS KMS Key Material Description"
        fields:
          keyMaterial:
            type: bindata_generic
          masterKey:
            type: awsMasterKey

    localMasterKey:
        description: "Local KMS Key Store Description"
        fields:
          provider:
            type: string
            default: '"local"'

    localMasterKeyAndMaterial:
        description: "Local KMS Key Material Description"
        fields:
          keyMaterial:
            type: bindata_generic
          masterKey:
            type: localMasterKey

    keyStoreRecord:
        description: "A V0 Key Store Record"
        fields:
          _id: uuid
          keyMaterial: bindata_generic
          creationDate: date
          updateDate: date
          status: int
          version:
            type: long
            default: 0
          masterKey: object
          keyAltNames:
              type: array<string>
              ignore: true

