Import("env")

env.Library(
    target= 'storage_artree_base',
    source= [
        'artree.cpp',
        'artree_cursor.cpp',
        'artree_delete.cpp',
        'artree_frame.cpp',
        'artree_index.cpp',
        'artree_iterator.cpp',
        'artree_kv_engine.cpp',
        'artree_nodes.cpp',
        'artree_oplog_store.cpp',
        'artree_ordered_list.cpp',
        'artree_records.cpp',
        'artree_recovery_unit.cpp',
        'artree_record_store.cpp',
        'artree_sorted_data_impl.cpp',
        'artree_util.cpp',
        ],
    LIBDEPS= [
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/db/catalog/collection_options',
        '$BUILD_DIR/mongo/db/index/index_descriptor',
        '$BUILD_DIR/mongo/db/storage/index_entry_comparison',
        '$BUILD_DIR/mongo/db/storage/key_string',
        '$BUILD_DIR/mongo/db/storage/oplog_hack',
        '$BUILD_DIR/mongo/util/concurrency/ticketholder',
        '$BUILD_DIR/mongo/db/concurrency/write_conflict_exception',
        '$BUILD_DIR/mongo/util/elapsed_tracker',
        '$BUILD_DIR/mongo/util/foundation',
        '$BUILD_DIR/mongo/util/processinfo',
        ]
    )

env.Library(
    target= 'storage_artree',
    source= [
        'artree_init.cpp',
        ],
    LIBDEPS= [
        'storage_artree_base',
        '$BUILD_DIR/mongo/db/storage/kv/kv_engine',
        ],
    LIBDEPS_DEPENDENTS=['$BUILD_DIR/mongo/db/serveronly']
    )

env.CppUnitTest(
    target='artree_record_store_test',
    source=[
        'artree_record_store_test.cpp'
        ],
    LIBDEPS=[
        'storage_artree_base',
        '$BUILD_DIR/mongo/db/storage/record_store_test_harness',
        ],
    )

env.CppUnitTest(
    target='artree_sorted_data_impl_test',
    source=[
        'artree_sorted_data_impl_test.cpp'
        ],
    LIBDEPS=[
        'storage_artree_base',
        '$BUILD_DIR/mongo/db/storage/sorted_data_interface_test_harness',
        ],
    )

