# -*- mode: python -*-

Import("env")

env.Library(
    target='mongot_options',
    source=[
        'mongot_options.cpp',
        env.Idlc('mongot_options.idl')[0],
    ],
    LIBDEPS_PRIVATE=[
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/idl/idl_parser',
        '$BUILD_DIR/mongo/idl/server_parameter',
        '$BUILD_DIR/mongo/util/net/network',
    ]
)
