"""Common AWS Constants"""

MOCK_AWS_ACCOUNT_ARN = 'arn:aws:iam::123456789012:user/Alice'
MOCK_AWS_ACCOUNT_ID = 'permanentuser'
MOCK_AWS_ACCOUNT_SECRET_KEY = 'FAKEFAKEFAKEFAKEFAKEfakefakefakefakefake'

MOCK_AWS_TEMP_ACCOUNT_ARN = 'arn:aws:iam::123456789012:user/Bob'
MOCK_AWS_TEMP_ACCOUNT_ID = 'tempuser'
MOCK_AWS_TEMP_ACCOUNT_SECRET_KEY = 'fakefakefakefakefakeFAKEFAKEFAKEFAKEFAKE'
MOCK_AWS_TEMP_ACCOUNT_SESSION_TOKEN = 'FAKETEMPORARYSESSIONTOKENfaketemporarysessiontoken'

MOCK_AWS_ACCOUNT_ASSUME_ROLE_ARN = 'arn:aws:sts::557821124784:assumed-role/cat/Puff'
MOCK_AWS_ACCOUNT_ASSUME_ROLE_GENERAL_ARN = 'arn:aws:sts::557821124784:assumed-role/cat/*'
MOCK_AWS_ACCOUNT_ASSUME_ROLE_ID = 'assumedrole'
MOCK_AWS_ACCOUNT_ASSUME_ROLE_SECRET_KEY = 'FAKEFAKEFAKEFAKEFAKEfakefakefakefakeFAKE'
MOCK_AWS_ACCOUNT_ASSUME_ROLE_SESSION_TOKEN = 'FAKETEMPORARYSESSIONTOKENfaketemporarysessionTOKEN'
