# Copyright (C) 2023-present MongoDB, Inc.

global:
    cpp_namespace: 'mongo'

imports:
    - "mongo/db/basic_types.idl"

structs:
    ManageSearchIndexRequest:
        description: "Command request for search index management host"
        # Not being strict because this is used to parse a command object that
        # contains other fields, like 'lsid'.
        strict: false
        fields:
            manageSearchIndex:
                description: "Command name field that holds the collection name value"
                type: string
                optional: false
            collectionUUID:
                description: "The collection UUID"
                type: uuid
                optional: false
            userCommand:
                description: "The original user search index command request"
                type: object
                optional: false
