# Copyright (C) 2019-present MongoDB, Inc.

global:
    cpp_namespace: 'mongo'
    cpp_includes:
      - 'search/mongot_options.h'

server_parameters:
    mongotHost:
        description: 'mongot host address'
        set_at: [ startup ]
        default: ''
        on_update: 'MongotParams::onSetHost'
        cpp_varname: 'globalMongotParams.host'
        validator:
            callback: 'MongotParams::onValidateHost'
    skipAuthenticationToMongot:
        description: 'Skip authentication for mongod->mongot connections, even if auth is enabled on mongod'
        set_at: [ startup ]
        cpp_varname: 'globalMongotParams.skipAuthToMongot'
        default: false 
    mongotConnectionPoolMinSize:
      description: <-
          The minimum number of connections for the TaskExecutor ConnectionPool used for outgoing 
          communication to mongot.
      set_at: [ startup, runtime ]
      cpp_varname: 'globalMongotParams.minConnections'
      validator:
          gte: 0
      default: 1
    mongotConnectionPoolMaxSize:
      description: <-
          The maximum number of connections for the TaskExecutor ConnectionPool used for outgoing 
          communication to mongot.
      set_at: [ startup, runtime ]
      cpp_varname: 'globalMongotParams.maxConnections'
      validator:
          gte: 1
      default: 32767
