# -*- mode: python -*-

Import('env')

env = env.Clone()

env.Library(
    target='encryption_schema_tree',
    source=[
        'encryption_schema_tree.cpp'
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/db/matcher/expressions',
    ]
)

env.CppUnitTest(
    target='encryption_schema_tree_test',
    source='encryption_schema_tree_test.cpp',
    LIBDEPS=[
        'encryption_schema_tree',
    ],
)

