#
# Copyright (C) 2022 MongoDB, Inc.  All Rights Reserved.
#

global:
    cpp_namespace: "mongo"

imports:
    - "mongo/db/basic_types.idl"
    - "mongo/s/sharding_types.idl"

structs:
    CollectionToRestore:
        description: >
            Structure for describing an allow-list collection that should be preserved.
        fields:
            ns:
                description: Namespace of the collection to preserve.
                type: namespacestring
            uuid:
                description: UUID of the collection to preserve.
                type: uuid

    ShardRenameMapping:
        description: >
            Structure for describing what changes to make to the sharding metadata for an individual
            shard.
        fields:
            sourceShardName:
                description: Existing name of the shard in the backup files.
                type: shard_id
            destinationShardName:
                description: Desired name of the shard in the cluster created for the restore.
                type: shard_id
            destinationShardConnectionString:
                description: >
                    The connection string for this shard in the destination cluster. In the
                    replSetName/member1,member2 format.
                type: string
