# -*- mode: python -*-

Import("env")
env.Library(
    target='magic_restore',
    source=[
        'magic_restore.cpp',
        'magic_restore_options.idl',
        'magic_restore_structs.idl',
    ],
    LIBDEPS_PRIVATE=[
        '$BUILD_DIR/mongo/db/mongod_options',
        '$BUILD_DIR/mongo/db/repl/replication_process',
        '$BUILD_DIR/mongo/db/repl/storage_interface',
        '$BUILD_DIR/mongo/db/server_options_core',
        '$BUILD_DIR/mongo/db/service_context',
        '$BUILD_DIR/mongo/idl/idl_parser',
        '$BUILD_DIR/mongo/util/namespace_string_database_name_util',
        '$BUILD_DIR/mongo/util/options_parser/options_parser',
    ],
    LIBDEPS_DEPENDENTS=[
        '$BUILD_DIR/mongo/db/mongod_initializers',
    ],
    LIBDEPS_TAGS=[
        'lint-allow-nonprivate-on-deps-dependents',
        'lint-allow-bidirectional-edges',
    ],
)
