#Copyright(C) 2023 MongoDB, Inc.All Rights Reserved.

global:
  cpp_namespace: "mongo"

imports:
  - "mongo/db/basic_types.idl"
  - "mongo/db/pipeline/value.idl"

structs:
  VectorSearchSpec:
    description: Specification for a $vectorSearch stage given in the full, explicit format.
    strict: true
    # Many of the $vectorSearch parameters are unique or complex types that are not supported
    # by the default IDL query shapification. We will mark these fields as 'parameter' here
    # so that they are passed through and manually override them when serializing the stage.
    query_shape_component: true
    fields:
      queryVector:
        description: The query vector.
        optional: false
        type: array<double>
        query_shape: parameter
      path:
        description: The path on which to search.
        optional: false
        type: string
        query_shape: literal
      index:
        description: The index to use.
        optional: true
        type: string
        query_shape: anonymize
      limit:
        description: Maximum number of documents to return.
        optional: false
        type: numeric
        query_shape: parameter
      numCandidates:
        description: Number of candidate documents mongot should consider.
        optional: true
        type: numeric
        query_shape: parameter
      filter:
        description: Pre-filter to apply before performing search.
        optional: true
        type: object
        query_shape: parameter

