# Copyright (C) 2020-present MongoDB, Inc. and subject to applicable commercial license.

# importCollection IDL File.

global:
  cpp_namespace: "mongo"

imports:
  - "mongo/db/basic_types.idl"
  - "live_import/collection_properties.idl"

commands:
  importCollection:
    command_name: importCollection
    cpp_name: ImportCollection
    description: "An enterprise-only mongod command for live import of collection files"
    namespace: type
    type: CollectionProperties
    api_version: ""
    strict: true
    fields:
      force:
        description: "Skip waiting for the dry run phase"
        type: safeBool
        default: false
