# Copyright (C) 2020-present MongoDB, Inc.  All Rights Reserved.

# importCollection IDL File.

global:
  cpp_namespace: "mongo"

imports:
  - "mongo/idl/basic_types.idl"
  - "live_import/collection_properties.idl"

commands:
  importCollection:
    command_name: importCollection
    cpp_name: ImportCollection
    description: "An enterprise-only mongod command for live import of collection files"
    namespace: type
    type: CollectionProperties
    strict: true
    fields:
      force:
        description: "Skip waiting for the dry run phase"
        type: safeBool
        default: false
