# Copyright (C) 2020-present MongoDB, Inc. and subject to applicable commercial license.

# voteCommitImportCollection IDL File.

global:
  cpp_namespace: "mongo"

imports:
  - "mongo/db/basic_types.idl"
  - "mongo/util/net/hostandport.idl"

commands:
  voteCommitImportCollection:
    command_name: voteCommitImportCollection
    cpp_name: VoteCommitImportCollection
    description: "An internal mongod command to coordinate live import of collection files in a
                  replica set"
    strict: true
    namespace: type
    api_version: ""
    type: uuid
    fields:
      from:
        type: HostAndPort
        description: "Replica set member identification"
      dryRunSuccess:
        description: "Result of the dryRun phase"
        type: safeBool
      reason:
        description: "Optional failure reason string"
        type: string
        optional: true
