# Copyright (C) 2019-present MongoDB, Inc.

global:
    cpp_namespace: "mongo"
    cpp_includes:
        - "watchdog/watchdog_mongod.h"

server_parameters:
    "watchdogPeriodSeconds":
        description: 'Watchdog Period (seconds)'
        set_at: [ startup, runtime ]
        cpp_vartype: 'AtomicWord<int>'
        cpp_varname: gWatchdogPeriodSeconds
        default: -1
        validator:
            callback: validateWatchdogPeriodSeconds
        on_update: onUpdateWatchdogPeriodSeconds
