# -*- mode: python; -*-

import SCons


Import('env')

env = env.Clone()

if env.TargetOSIs('windows'):
    env.Append(
        CCFLAGS=[
            # C5033: 'register' is no longer a supported storage
            # class. The snmp library still uses the 'register'
            # keyword.
            "/wd5033",
        ],
    )

env.Library(
    target='mongosnmp',
    source=[
        'serverstatus_client.cpp',
        'snmp.cpp',
        'snmp_oid.cpp',
        'snmp_options.cpp',
        'snmp_options.idl',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/client/clientdriver_network',
        '$BUILD_DIR/mongo/db/bson/dotted_path_support',
        '$BUILD_DIR/mongo/db/dbdirectclient',
        '$BUILD_DIR/mongo/db/initialize_snmp',
        '$BUILD_DIR/mongo/db/repl/repl_coordinator_interface',
        '$BUILD_DIR/mongo/db/repl/repl_settings',
        '$BUILD_DIR/mongo/util/processinfo',
    ],
    LIBDEPS_PRIVATE=[
        '$BUILD_DIR/mongo/util/options_parser/options_parser',
    ],
    LIBDEPS_DEPENDENTS=['$BUILD_DIR/mongo/db/mongod_initializers'],
    SYSLIBDEPS=env.get('SNMP_SYSLIBDEPS', []),
    LIBDEPS_TAGS=[
        'lint-allow-nonprivate-on-deps-dependents',
    ],
)
