# Copyright (C) 2019-present MongoDB, Inc. and subject to applicable commercial license.

global:
    cpp_namespace: "mongo"
    cpp_includes:
        - "mongo/util/net/ssl_options.h"
    configs:
        section: 'Encryption at rest options'
        source: [ cli, ini, yaml ]

configs:
    "security.kmip.keyIdentifier":
        description: 'KMIP unique identifier for existing key to use'
        short_name: kmipKeyIdentifier
        arg_vartype: String
    "security.kmip.serverName":
        description: 'KMIP server host name'
        short_name: kmipServerName
        arg_vartype: String
    "security.kmip.port":
        description: 'KMIP server port (defaults to 5696)'
        short_name: kmipPort
        arg_vartype: Int
        requires: "security.kmip.serverName"
    "security.kmip.connectTimeoutMS":
        description: 'KMIP server connect timeout (milliseconds)'
        short_name: kmipConnectTimeoutMS
        arg_vartype: Int
        default: 5000
        validator:
            gte: 1000
    "security.kmip.connectRetries":
        description: 'If connecting to a KMIP server times out, how many times should we retry.'
        short_name: kmipConnectRetries
        arg_vartype: Int
        default: 0
        validator:
            gte: 0
    "security.kmip.useLegacyProtocol":
        description: 'Use KMIP protocol version 1.0 instead of the default 1.2.'
        short_name: kmipUseLegacyProtocol
        arg_vartype: Bool
        default: false
    "security.kmip.clientCertificateFile":
        description: 'Client certificate for authenticating to KMIP server'
        short_name: kmipClientCertificateFile
        arg_vartype: String
        requires: "security.kmip.serverName"
    "security.kmip.clientCertificatePassword":
        description: 'Client certificate for authenticating Mongo to KMIP server'
        short_name: kmipClientCertificatePassword
        arg_vartype: String
        redact: true
        requires: "security.kmip.clientCertificateFile"
    "security.kmip.serverCAFile":
        description: 'CA File for validating connection to KMIP server'
        short_name: kmipServerCAFile
        arg_vartype: String
    "security.kmip.clientCertificateSelector":
        description: 'Client Certificate in system store for authenticating to KMIP server'
        short_name: kmipClientCertificateSelector
        arg_vartype: String
        conflicts:
            - "security.kmip.clientCertificateFile"
            - "security.kmip.clientCertificatePassword"
        condition:
            preprocessor: 'defined(MONGO_CONFIG_SSL_CERTIFICATE_SELECTORS)'
    "security.kmip.keyStatePollingSeconds":
        description: 'Frequency for node to poll KMIP server for key active state'
        short_name: kmipKeyStatePollingSeconds
        arg_vartype: Int
        requires: "security.kmip.serverName"
