# -*- mode: python -*-

Import("env")

env = env.Clone()

if "encryptdb" in env["MONGO_ENTERPRISE_FEATURES"] or "audit" in env["MONGO_ENTERPRISE_FEATURES"]:
    env.CppUnitTest(
        target="kmip_test",
        source=[],
        LIBDEPS=[],
    )
