# -*- mode: python -*-

Import("env")

env = env.Clone()

env.CppUnitTest(
    target="metric_manager_test",
    source=[
        "metric_manager_test.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/base",
        "../streams_util",
    ],
)
