# Copyright (C) 2022-present MongoDB, Inc.

global:
    cpp_namespace: "mongo::auth"

imports:
    - "mongo/db/basic_types.idl"

structs:
    IDPConfiguration:
        description: A single IdP definition.
        fields:
            issuer:
                description: The issuer we're accepting Access Tokens from.
                    Must match the `iss` field in any JWT used for authentication.
                    Used as the symbolic name to identify this IDP by the IDPManager and must be unique.
                    Used for logging purposes.
                    Used in constructing UserName and RoleName identifiers.
                type: string
            audience:
                description: Server identifier provided by the IDP to uniquely identify the cluster.
                type: string
            authNamePrefix:
                description:
                    Unique prefix applied to all generated UserName and RoleNames used in authorization.
                    Must not contain solidus.
                type: string
            matchPattern:
                description:
                    Regex pattern applied to an advertised principal name to determine if this IDP should be used.
                    Array order determines priority when multiple matchPatterns result in a match.
                    Required when more than one IdP defined, discouraged otherwise.
                type: string
                optional: true # Required when more than one IDP configured.
            supportsHumanFlows:
                description:
                    Flag indicating whether the IdP supports client-side token acquisition flows that
                    require a clientId. If set to false, the server will accept a configuration that
                    does not specify a clientId and will omit it in its first SASL reply to drivers,
                    which are expected to be able to acquire the token without using a clientId.
                type: bool
                default: true
            clientId:
                description: Opaque client identifier provided by the IDP to uniquely identify the client which requests tokens.
                type: string
                optional: true # Required when supportsHumanFlows is true.
            requestScopes:
                description: A list of additional scopes the client should request when authenticating with its IDP.
                type: array<string>
                optional: true
            principalName:
                description: The claim to be extracted from a presented token, and used as the bearer's principal name.
                type: string
                default: '"sub"'
            useAuthorizationClaim:
                description: 
                    Flag indicating whether the server needs to extract MongoDB role names 
                    from a claim on the token.
                type: bool
                default: true
            authorizationClaim:
                description: Claim to be extracted from Access Token containing MongoDB role names.
                type: string
                optional: true # Must be specified if useAuthorizationClaim is true.
            logClaims:
                description: List of Access Token claims to include in log messages on authentication completion.
                type: array<string>
                optional: true # Defaults to ['iss', 'sub'] in setParameter parsing
            JWKSPollSecs:
                description:
                    Frequency, in seconds, to request an updated JWKS manifest.
                    A setting of 0 will disable polling.
                type: seconds
                default: 86400 # One day


server_parameters:
    oidcIdentityProviders:
        description: Configuration of all IdentityProviders to use for OIDC.
        set_at: [startup, runtime]
        cpp_class:
            name: OIDCIdentityProvidersParameter
            override_set: true
            override_validate: true
        redact: false
