# Copyright (C) 2022-present MongoDB, Inc.

global:
    cpp_namespace: "mongo"

imports:
    - "mongo/idl/basic_types.idl"

structs:
    OIDCMechanismClientStep1:
        description: "Client's opening request in saslStart"
        fields:
            n:
                description: "Principal name client intends to authenticate as"
                cpp_name: principalName
                type: string
                optional: true

    OIDCMechanismServerStep1:
        description: "Server's reply to {saslStart: 1, mechanism: 'MONGODB-OIDC'}"
        fields:
            idp:
                description: "URL where the IDP may be contacted for authn and token generation"
                type: string
            clientId:
                description: "Unique client ID for this OIDC client"
                type: string
            clientSecret:
                description: "Secret used when communicating with IDP"
                type: string

    OIDCMechanismClientStep2:
        description: "Client's request with signed token"
        fields:
            jwt:
                description: "Compact serialized JWT with signature"
                cpp_name: JWT
                type: string

