# Copyright (C) 2019-present MongoDB, Inc.

global:
    cpp_namespace: "mongo"
    cpp_includes:
        - "sasl/sasl_aws_server_protocol.h"

server_parameters:
    awsSTSUrl:
        description: "Parameter to override AWS STS HTTP Url"
        set_at: startup
        default: "https://sts.amazonaws.com"
        cpp_varname: "awsIam::saslAWSGlobalParams.awsSTSUrl"
