# -*- mode: python; -*-

Import("env")
Import("ssl_provider")

env = env.Clone()

if env.TargetOSIs("windows"):
    env.SharedLibrary(
        target="cyrus_sasl_windows_test_plugin",
        source=["cyrus_sasl_windows_test_plugin.cpp"],
        LIBDEPS_NO_INHERIT=[
            "$BUILD_DIR/third_party/tcmalloc/tcmalloc",
            "$BUILD_DIR/third_party/gperftools/tcmalloc_minimal",
        ],
        AIB_COMPONENT="dist-test",
    )

if ssl_provider == "openssl":
    env.CppUnitTest(
        target="sasl_oidc_server_test",
        source=[],
        LIBDEPS=[],
    )

env.CppUnitTest(
    target="sasl_aws_protocol_test",
    source=[],
    LIBDEPS=[],
)

if not env.TargetOSIs("windows"):
    env.CppUnitTest(
        target="sasl_authentication_session_gssapi_test",
        source=[],
        LIBDEPS=[],
    )
