# -*- mode: python; -*-

Import("env")
Import("ssl_provider")

env = env.Clone()

if env.TargetOSIs("windows"):
    env.BazelSharedLibrary(
        target="cyrus_sasl_windows_test_plugin",
        source=[],
        AIB_COMPONENT="dist-test",
    )

if ssl_provider == "openssl":
    env.CppUnitTest(
        target="sasl_oidc_server_test",
        source=[],
        LIBDEPS=[],
    )

env.CppUnitTest(
    target="sasl_aws_protocol_test",
    source=[],
    LIBDEPS=[],
)

if not env.TargetOSIs("windows"):
    env.CppUnitTest(
        target="sasl_authentication_session_gssapi_test",
        source=[],
        LIBDEPS=[],
    )
