#
#    Copyright (C) 2023-present MongoDB, Inc.
#

global:
    cpp_namespace: "mongo"

imports:
    - "mongo/db/basic_types.idl"

# TOOD(SERVER-78463): Version all these structs so updates are easily supported.
structs:
    WatermarkState:
        strict: true
        description: Watermark state in checkpoint data.
        fields:
            eventTimeMs:
                type: safeInt64

    KafkaPartitionCheckpointState:
        strict: true
        description: Checkpoint state of a single Kafka topic partition in a $source operator.
        fields:
            partition:
                description: Partition number.
                type: int
            offset:
                description: Log offset of the partition.
                type: safeInt64
            watermark:
                description: Event time watermark of the partition.
                type: WatermarkState
                optional: true

    KafkaSourceCheckpointState:
        description: Checkpoint state of a Kafka $source operator.
        strict: true
        fields:
            partitions:
                type: array<KafkaPartitionCheckpointState>
    
    ChangeStreamSourceCheckpointState:
        description: "Checkpoint state of a MongoDB changestream $source operator."
        strict: true
        fields:
            startingPoint:
                type:
                    variant: [object, timestamp]
                # In written checkpoint data, startingPoint will always be set.
                # This is marked as optional only so the ChangeStreamSourceOperator can
                # track when a startingPoint has not yet been chosen.
                optional: true
                description: "If object: the resumeToken to start after. If timestamp: the operation time to start at."
            watermark:
                description: Event time watermark of the changestream.
                type: WatermarkState
                optional: true

    OperatorState:
        strict: true
        description: The serialized state of a single operator in a checkpoint.
        fields:
            _id:
                description: A primary key string ID that identifies the operator within a checkpoint.
                type: string
            state:
                description: Operator state in the checkpoint.
                type: object

    CheckpointInfo:
        strict: true
        description: A CheckpointInfo document is written when a checkpoint is committed. Corresponding OperatorState is considered valid when this document exists.
        fields:
            _id:
                description: A string ID in the form checkpoint-{tenantId}-{streamProcessorId}-{timestamp}.
                type: string

    WindowOperatorStateFastMode:
        strict: true
        description: WindowOperator state when using fast mode checkpointing.
        fields:
            minimumWindowStartTime:
                type: safeInt64
            
