#
#    Copyright (C) 2023-present MongoDB, Inc. and subject to applicable commercial license.
#

global:
    cpp_namespace: "mongo"

imports:
    - "mongo/db/basic_types.idl"

enums:
    HttpMethod:
        type: string
        description: "The supported HTTP Verbs. The enums have the 'Method' prefix because 'delete' conflicts with a builtin C++ keyword."
        values:
            MethodGet: "GET"
            MethodPost: "POST"
            MethodPatch: "PATCH"
            MethodPut: "PUT"
            MethodDelete: "DELETE"

structs:

    MetricLabel:
        description: "A kay-value label associated with a metric"
        fields:
            key:
                description: Label key.
                type: string
            value:
                description: Label value.
                type: string


    CounterMetricValue:
        description: "A counter metric sent in the response message for streams_getMetrics command"
        fields:
            name:
                description: Name of the metric.
                type: string
            description:
                description: Description of the metric.
                type: string
            value:
                description: Current value of the metric.
                type: safeInt64
            labels:
                description: Labels associated with the metric.
                type: array<MetricLabel>

    GaugeMetricValue:
        description: "A gauge metric sent in the response message for streams_getMetrics command"
        fields:
            name:
                description: Name of the metric.
                type: string
            description:
                description: Description of the metric.
                type: string
            value:
                description: Current value of the metric.
                type: safeDouble
            labels:
                description: Labels associated with the metric.
                type: array<MetricLabel>

    HistogramBucket:
        description: A single bucket part of a histogram.
        fields:
            upperBound:
                description: >
                    Inclusive upper bound of the bucket. There will always be a single bucket with
                    no upper bound, which will represent the catch all +Infinity bucket.
                type: safeInt64
                optional: true
            count:
                description: Number of observations seen within this bucket.
                type: safeInt64

    HistogramMetricValue:
        description: "A histogram metric sent in the response message for streams_getMetrics command"
        fields:
            name:
                description: Name of the metric.
                type: string
            description:
                description: Description of the metric.
                type: string
            labels:
                description: Labels associated with the metric.
                type: array<MetricLabel>
            buckets:
                description: Buckets of the histogram.
                type: array<HistogramBucket>
