#
#    Copyright (C) 2023-present MongoDB, Inc.
#

global:
    cpp_namespace: "mongo"

imports:
    - "mongo/db/basic_types.idl"

enums:
    ConnectionType:
        description: "Connection type"
        type: string
        values:
            Kafka: "kafka"
            Atlas: "atlas"

structs:
    KafkaConnectionOptions:
        description: "Kafka connection options."
        strict: true
        fields:
            bootstrapServers:
                description: "Comma separate string of bootstrapServer network locations."
                type: string
            isTestKafka:
                description: "If set and true, use a mock Kafka connection."
                type: bool
                optional: true

    AtlasConnectionOptions:
        description: "Atlas connection options."
        strict: true
        fields:
            uri:
                description: "Atlas connection URI"
                type: string

    Connection:
        description: "Connection registry information."
        strict: true
        fields:
            name:
                description: "Name of this connection."
                type: string
            type:
                description: "Type of this connection e.g. kafka, atlas"
                type: ConnectionType
            options:
                description: "Options specific to the connectionType."
                type: object
