#
#    Copyright (C) 2023-present MongoDB, Inc.
#

global:
    cpp_namespace: "mongo"

imports:
    - "mongo/db/basic_types.idl"

enums:
    StreamMetaSourceType:
        description: "Source type"
        type: string
        values:
            Kafka: "kafka"
            Atlas: "atlas"
            Generated: "generated"

structs:
    KafkaHeader:
        description: "A header for a Kafka document."
        fields:
            k:
                description: "Key of this header."
                type: string
            v:
                description: "Value of this header."
                type: bindata_generic

    CheckpointDescription:
        description: "A high level description about a checkpoint, useful for debugging purposes."
        fields:
            id:
                description: The checkpoint ID.
                type: safeInt64
            filepath:
                description: On-disk location of the checkpoint manifest.
                type: string
            checkpointSizeBytes:
                description: The size of the checkpoint that was written/restored
                type: safeInt64
            checkpointTimestamp:
                description: The time point at which this checkpoint was committed
                type: date
            writeDurationMs:
                description: The time (in milliseconds) it took to write this checkpoint.
                type: milliseconds
            restoreDurationMs:
                description: The time (in milliseconds) it took to restore from this checkpoint, if applicable.
                type: milliseconds
                default: 0
            sourceState:
                description: $source state in this checkpoint.
                type: object
                optional: true

    OperatorStatsDoc:
        description: Operator specific stats.
        strict: true
        fields:
            name:
                description: Name of the operator.
                type: string
            inputDocs:
                description: Total number of input docs read, including docs that were rejected.
                type: safeInt64
            inputBytes:
                description: Total number of input bytes read, including docs that were rejected.
                type: safeInt64
            outputDocs:
                description: Total number of output docs emitted.
                type: safeInt64
            outputBytes:
                description: Total number of output bytes emitted.
                type: safeInt64
            dlqDocs:
                description: Total number of input docs that were rejected and sent to the dead letter queue.
                type: safeInt64
            dlqBytes:
                description: Total number of bytes sent to the dead letter queue.
                type: safeInt64
            stateSize:
                description: Total state size of the operator.
                type: safeInt64

    StreamMeta:
        description: "_stream_meta object definition"
        strict: true
        fields:
            sourceType:
                description: "Type of source e.g. kafka, atlas"
                type: StreamMetaSourceType
                optional: true
            sourcePartition:
                description: "Source partition e.g. Kafka partition"
                type: int
                optional: true
            sourceOffset:
                description: "Offset of this document in the source partition"
                type: safeInt64
                optional: true
            sourceKey:
                description: "Key of this Kafka document"
                type: bindata_generic
                optional: true
            sourceHeaders:
                description: "Headers of this Kafka document"
                type: array<KafkaHeader>
                optional: true
            windowStart:
                description: "Window start timestamp"
                type: date
                optional: true
            windowEnd:
                description: "Window end timestamp"
                type: date
                optional: true

    SampleDataSourceSolarSpecObs:
        description: obs field in the SampleDataSourceSolarSpec.
        strict: true
        fields:
            watts:
                type: int
            temp:
                type: int

    SampleDataSourceSolarSpec:
        description: Specifies the data generated by the solar sample data $source.
        strict: true
        fields:
            device_id:
                type: string
            group_id:
                type: int
            timestamp:
                type: string
            max_watts:
                type: int
            event_type:
                type: int
            obs:
                type: SampleDataSourceSolarSpecObs
                optional: true
            event_details:
                type: string
                optional: true
