#
#    Copyright (C) 2023-present MongoDB, Inc. and subject to applicable commercial license.
#

global:
    cpp_namespace: "mongo"

imports:
    - "mongo/db/basic_types.idl"
    - "mongo/db/pipeline/value.idl"
    - "mongo/db/modules/enterprise/src/streams/exec/common.idl"

enums:
    StreamMetaSourceType:
        description: "Source type"
        type: string
        values:
            Kafka: "kafka"
            Atlas: "atlas"
            Generated: "generated"

structs:
    KafkaHeader:
        description: "A header for a Kafka document."
        strict: false
        fields:
            k:
                description: "Key of this header."
                type: string
            v:
                description: "Value of this header."
                type:
                    variant: [bindata_generic, string, object, int, long, double]

    CheckpointDescription:
        description: "A high level description about a checkpoint, useful for debugging purposes."
        strict: false
        fields:
            id:
                description: The checkpoint ID.
                type: safeInt64
            filepath:
                description: On-disk location of the checkpoint manifest.
                type: string
            checkpointSizeBytes:
                description: The size of the checkpoint that was written/restored
                type: safeInt64
            checkpointTimestamp:
                description: The time point at which this checkpoint was committed
                type: date
            writeDurationMs:
                description: The time (in milliseconds) it took to write this checkpoint.
                type: milliseconds
            restoreDurationMs:
                description: The time (in milliseconds) it took to restore from this checkpoint, if applicable.
                type: milliseconds
                default: 0
            sourceState:
                description: $source state in this checkpoint.
                type: object
                optional: true

    OperatorStatsDoc:
        description: Operator specific stats.
        strict: false
        fields:
            name:
                description: Name of the operator.
                type: string
            inputDocs:
                description: Total number of input docs read, including docs that were rejected.
                type: safeInt64
                default: 0
            inputBytes:
                description: Total number of input bytes read, including docs that were rejected.
                type: safeInt64
                default: 0
            outputDocs:
                description: Total number of output docs emitted.
                type: safeInt64
                default: 0
            outputBytes:
                description: Total number of output bytes emitted.
                type: safeInt64
                default: 0
            dlqDocs:
                description: Total number of input docs that were rejected and sent to the dead letter queue.
                type: safeInt64
                default: 0
            dlqBytes:
                description: Total number of bytes sent to the dead letter queue.
                type: safeInt64
                default: 0
            stateSize:
                description: Total state size of the operator.
                type: safeInt64
                default: 0
            executionTime:
                description: Total execution time of the operator.
                type: milliseconds 
                default: 0

    StreamMetaSource:
        description: "The definition of the source field of stream metadata"
        strict: false
        fields:
            type:
                description: "Type of source e.g. kafka, atlas"
                type: StreamMetaSourceType
                optional: true
            topic:
                description: "Topic of this Kafka document"
                type: string
                optional: true
            partition:
                description: "Source partition e.g. Kafka partition"
                type: int
                optional: true
            offset:
                description: "Offset of this document in the source partition"
                type: safeInt64
                optional: true
            key:
                description: "Key of this Kafka document"
                type:
                    variant: [bindata_generic, string, object, int, long, double]
                optional: true
            headers:
                description: "Headers of this Kafka document"
                type: array<KafkaHeader>
                optional: true

    StreamMetaWindow:
        description: "The definition of the window field of stream metadata"
        strict: false
        fields:
            start:
                description: "Window start timestamp"
                type: date
                optional: true
            end:
                description: "Window end timestamp"
                type: date
                optional: true
            # The partition field is only populated for session windows.
            partition:
                # TODO(SERVER-92473): Project partition into the document _stream_meta.
                description: "Value identifier for partition"
                type: Value
                optional: true
            # Window ID doesn't get projected to _stream_meta.
            windowID:
                description: "Integer identifier for session window"
                type: int
                optional: true

    StreamMetaHttps:
        description: "The definition of the https field of stream metadata"
        strict: false
        fields:
            url:
                description: "The URL of the https request"
                type: string
            method:
                description: "The HTTP verb used when making a request"
                type: HttpMethod
            httpStatusCode:
                description: "The HTTP status code returned in the response"
                type: int
            responseTimeMs:
                description: "The amount time elapsed from when the request was sent and when a response was received"
                type: int
    
    StreamMeta:
        description: "_stream_meta object definition"
        strict: false
        fields:
            source:
                description: "source field of _stream_meta object"
                type: StreamMetaSource
                optional: true
            window:
                description: "window field of _stream_meta object"
                type: StreamMetaWindow
                optional: true
            https:
                description: "https field of _stream_meta object"
                type: StreamMetaHttps
                optional: true

    SampleDataSourceSolarSpecObs:
        description: obs field in the SampleDataSourceSolarSpec.
        strict: false
        fields:
            watts:
                type: int
            temp:
                type: int

    SampleDataSourceSolarSpec:
        description: Specifies the data generated by the solar sample data $source.
        strict: false
        fields:
            device_id:
                type: string
            group_id:
                type: int
            timestamp:
                type: string
            max_watts:
                type: int
            event_type:
                type: int
            obs:
                type: SampleDataSourceSolarSpecObs
                optional: true
            event_details:
                type: string
                optional: true

    KafkaConnectAuthSpec:
        description: Specifies the authentication payload for VPC peering authentication headers.
        strict: false
        fields:
            url:
                type: string
            timestamp:
                type: string
            randomSeed:
                type: string
