#
#    Copyright (C) 2023-present MongoDB, Inc.
#

global:
    cpp_namespace: "mongo"

imports:
    - "mongo/db/basic_types.idl"
    - "mongo/db/modules/enterprise/src/streams/exec/common_types.idl"

structs:
    KafkaSourceOptions:
        description: "$source stage options for Kafka sources."
        strict: true
        fields:
            connectionName:
                description: "Name of the Kafka source, should be the same as the Connection.name."
                type: string
            topic:
                description: "Topic name to use for the source data."
                type: string
            timeField:
                description: "Expression for computing the event time on a Document."
                type: object
                optional: true
            tsFieldOverride:
                description: "The $source stage will project the timestamp for a document into this field."
                type: string
                optional: true
            allowedLateness:
                description: "The allowed lateness for documents in a window."
                type: StreamTimeDuration
                optional: true
            partitionCount:
                description: "The number of partitions in the source."
                type: int
                validator: {gte: 1}
