#
#    Copyright (C) 2023-present MongoDB, Inc. and subject to applicable commercial license.
#

global:
    cpp_namespace: "mongo"
    cpp_includes:
        - "mongo/db/pipeline/aggregation_request_helper.h"
        - "mongo/db/pipeline/name_expression.h"

imports:
    - "mongo/db/basic_types.idl"
    - "mongo/db/pipeline/document_source_merge.idl"
    - "mongo/db/pipeline/document_source_change_stream.idl"
    - "mongo/db/pipeline/name_expression.idl"
    - "mongo/db/timeseries/timeseries.idl"
    - "mongo/db/modules/enterprise/src/streams/exec/common.idl"

types:
    pipeline:
        bson_serialization_type: any
        description: "An array of objects specifying an operator's inner pipeline."
        cpp_type: "std::vector<mongo::BSONObj>"
        deserializer: ::mongo::parsePipelineFromBSON

enums:
    ConnectionType:
        description: "Connection type"
        type: string
        values:
            Kafka: "kafka"
            Atlas: "atlas"
            SampleSolar: "sample_solar"
            InMemory: "in_memory"
            HTTPS: "https"

    StreamsValidationAction:
        description: "validation action for $validate stage"
        type: string
        values:
            Discard: "discard"
            Dlq: "dlq"

    StreamTimeUnit:
        description: "Units of time for streaming pipeline stages."
        type: string
        values:
            Millisecond: "ms"
            Second: "second"
            Minute: "minute"
            Hour: "hour"
            Day: "day"

    KafkaSourceStartAt:
        description: "Start position options for Kafka."
        type: string
        values:
            Earliest: "earliest"
            Latest: "latest"

    KafkaSourceAutoOffsetReset:
        description: "auto.offset.reset options for the kafka config."
        type: string
        values:
            Smallest: "smallest"
            Earliest: "earliest"
            Beginning: "beginning"
            Largest: "largest"
            Latest: "latest"
            End: "end"

    DateSerializationFormat:
        description: "Format to serialize date values."
        type: string
        values:
            Default: "default"
            ISO8601: "ISO8601"

    KafkaAuthSaslMechanism:
        type: string
        description: "Kafka sasl.mechanism options."
        values:
            Plain: "PLAIN"
            ScramSHA256: "SCRAM-SHA-256"
            ScramSHA512: "SCRAM-SHA-512"

    KafkaAuthSecurityProtocol:
        type: string
        description: "Kafka security.protocol options."
        values:
            Plaintext: "PLAINTEXT"
            SaslPlaintext: "SASL_PLAINTEXT"
            SaslSSL: "SASL_SSL"

    KafkaTLSValidationAlgorithm:
        type: string
        description: "Kafka TLS certificate validation algorithm."
        values:
            HTTPS: "https"
            None: "none"
    
    KafkaEmitJsonStringFormat:
        type: string
        description: "Json String format."
        values:
            RelaxedJson: "relaxedJson"
            CanonicalJson: "canonicalJson"

    KafkaKeyFormat:
        description: "The data type used to serialize and deserialize Kafka key"
        type: string
        values:
            BinData: "binData"
            String: "string"
            Json: "json"
            # The int and long are big-endian to align with the Java serializer/deserializer for Kafka
            Int: "int"
            Long: "long"
            Double: "double"

    KafkaSourceKeyFormatError:
        description: "How to handle error during Kafka key deserialization"
        type: string
        values:
            Dlq: "dlq"
            PassThrough: "passThrough"

    KafkaCompressionType:
        type: string
        description: "The supported kafka compression types"
        values:
            none: "none"
            gzip: "gzip"
            snappy: "snappy"
            lz4: "lz4"
            zstd: "zstd"

    KafkaAcks:
        type: string
        description: "The supported kafka acks"
        values:
            All: "all"
            Negative: "-1"
            None: "0"
            One: "1"

    OnError:
        type: string
        description: "Describes how a document processing error should be handled"
        values:
            DLQ: "dlq"
            Ignore: "ignore"
            Fail: "fail"

    WindowBoundary:
        type: string
        description: Window boundary
        values:
            processingTime: "processingTime"
            eventTime: "eventTime"

structs:
    StreamTimeDuration:
        description: "A duration of time."
        strict: true
        fields:
            size:
                description: "The size of the duration in terms of unit."
                type: int
                validator: {gte: 0}
            unit:
                description: "The time unit used for the duration."
                type: StreamTimeUnit

    TimeOffset:
        description: "A time offset from the UTC."
        strict: true
        fields:
            offsetFromUtc:
                description: "The offset from the UTC in terms of unit."
                type: int
            unit:
                description: "The time unit used for the offset."
                type: StreamTimeUnit

    KafkaAuthOptions:
        description: "Auth related options for a Kafka connection."
        strict: true
        fields:
            saslMechanism:
                description: "sasl.mechanism Kafka config."
                type: KafkaAuthSaslMechanism
                optional: true
            saslUsername:
                description: "sasl.username Kafka config."
                type: string
                optional: true
            saslPassword:
                description: "sasl.password Kafka config."
                type: string
                optional: true
            securityProtocol:
                description: "security.protocol Kafka config."
                type: KafkaAuthSecurityProtocol
                optional: true
            caCertificatePath:
                description: "Path to Kafka TLS CA certificate for validation."
                type: string
                optional: true
            validateTLSAlgorithm:
                description: "If using TLS, specify algorithm to verify hostnames (https or none)."
                type: KafkaTLSValidationAlgorithm
                optional: true

    KafkaConnectionOptions:
        description: "Kafka connection options."
        strict: false
        fields:
            bootstrapServers:
                description: "Comma separate string of bootstrapServer network locations."
                type: string
            isTestKafka:
                description: "If set and true, use a mock Kafka connection."
                type: bool
                optional: true
            auth:
                description: "Kafka config values related to auth, like sasl.username."
                type: KafkaAuthOptions
                optional: true
            gwproxyEndpoint:
                description: "Hostname or IP address of GWProxy endpoint for VPC peering sessions."
                type: string
                optional: true
            gwproxyKey:
                description: "Pre-shared 32-byte (AES-256) key for GWProxy authentication for VPC peering sessions."
                type: string
                optional: true
            configurations:
                description: "Kafka config values that let users customize their kafka source and/or sink."
                type: object
                optional: true

    HttpsConnectionOptions:
        description: "HTTPS connection options."
        strict: true
        fields:
            url:
                description: "The URL of the connection."
                type: string
            headers:
                description: "The headers to send to the url."
                type: object
                optional: true

    AtlasConnectionOptions:
        description: "Atlas connection options."
        strict: true
        fields:
            uri:
                description: "Atlas connection URI"
                type: string
            pemFile:
                description: "Path to PEM file for authentication to an Atlas cluster."
                type: string
                optional: true
            caFile:
                description: "Path to CA file for verifying the PEM file above."
                type: string
                optional: true

    Connection:
        description: "Connection registry information."
        strict: true
        fields:
            name:
                description: "Name of this connection."
                type: string
            type:
                description: "Type of this connection e.g. kafka, atlas"
                type: ConnectionType
            options:
                description: "Options specific to the connectionType."
                type: object

    GeneratedDataSourceOptions:
        description: "$source stage options for a generated data source, in-memory or sample data"
        strict: true
        fields:
            connectionName:
                description: "Name of the data source, should be the same as the Connection.name."
                type: string
            timeField:
                description: "Expression for computing the event time on a Document."
                type: 
                    variant: [object, string]
                optional: true
            tsFieldOverride:
                description: "The $source stage will project the timestamp for a document into this field."
                type: string
                optional: true
            tsFieldName:
                description: "The $source stage will project the timestamp for a document into this field."
                type: string
                optional: true
            streamMetaFieldName:
                description: "The field name that the stream metadata is projected to. If set to empty, the stream metadata will not be projected into the documents."
                type: string
                default: '"_stream_meta"'

    DocumentsDataSourceOptions:
        description: "Optional configuration options for a document list $source."
        strict: true
        fields:
            timeField:
                description: "Expression for computing the event time on a Document."
                type: 
                    variant: [object, string]
                optional: true
            tsFieldOverride:
                description: "The $source stage will project the timestamp for a document into this field."
                type: string
                optional: true
            tsFieldName:
                description: "The $source stage will project the timestamp for a document into this field."
                type: string
                optional: true
            streamMetaFieldName:
                description: "The field name that the stream metadata is projected to. If set to empty, the stream metadata will not be projected into the documents."
                type: string
                default: '"_stream_meta"'
            documents:
                description: "List of documents or an expression that generates a list of documents from this source."
                type:
                    variant: [array<object>, object]

    KafkaSourceConfigOptions:
        description: "Optional configuration options for a Kafka $source."
        strict: true
        fields:
            auto_offset_reset:
                description: >
                    Logical offset to use when there is no last checkpoint or committed offset. Options can either by the earliest offset
                    available ["smallest", "earliest", "beginning"] or the latest offset available ["largest", "latest", "end"]. Defaults
                    to using the latest offset available.
                type: KafkaSourceAutoOffsetReset
                default: Latest
                cpp_name: autoOffsetReset
            enable_auto_commit:
                description: "Controls whether to update consumer group offsets when reading input documents (true) or whenever a checkpoint occurs (false)."
                type: bool
                cpp_name: enableAutoCommit
                optional: true
            group_id:
                description: "Kafka consumer group ID to use for this stream processor. If one is not set, then one will be auto-generated for non ephemeral stream processors."
                type: string
                optional: true
                cpp_name: groupId
            keyFormat:
                description: "The data type used to deserialize Kafka key"
                type: KafkaKeyFormat
                default: BinData
            keyFormatError:
                description: "How to handle error during Kafka key deserialization"
                type: KafkaSourceKeyFormatError
                default: Dlq

    ParsedConnectionInfo:
        description: Connection information returned in parseOnly start requests.
        strict: false
        fields:
            name:
                description: Name of the connection.
                type: string
            stage:
                description: Stage name the connection is associated with.
                type: string
                optional: true

    KafkaSinkConfigOptions:
        description: "Optional configuration options for a Kafka Sink."
        strict: true
        fields:
            key:
                type:
                    variant: [object, string]
                description: "The expression that evaluates to the key of the Kafka message."
                optional: true
            keyFormat:
                description: "The data type used to serialize Kafka key"
                type: KafkaKeyFormat
                optional: true
            headers:
                type:
                    variant: [object, string]
                description: "The expression that evaluates to the headers of the Kafka message."
                optional: true
            outputFormat:
                description: "Output format type relaxedJson | canonicalJson, default relaxedJson"
                optional: true
                cpp_name: outputFormat
                type: KafkaEmitJsonStringFormat
                default: RelaxedJson
            compression_type:
                description: "Kafka compression.type options."
                optional: true
                cpp_name: compressionType
                type: KafkaCompressionType
            acks:
                description: "The number of acknowledgements the producer requires kafka to have received"
                optional: true
                type: KafkaAcks
            dateFormat:
                description: "Date format, might override the default date format in the outputFormat."
                type: DateSerializationFormat
                default: Default

    KafkaSourceOptions:
        description: "$source stage options for Kafka sources."
        strict: true
        fields:
            connectionName:
                description: "Name of the Kafka source, should be the same as the Connection.name."
                type: string
            topic:
                description: "Topic(s) to use for the source data."
                type:
                    variant: [string, array<string>]
            timeField:
                description: "Expression for computing the event time on a Document."
                type:
                    variant: [object, string]
                optional: true
            tsFieldOverride:
                description: "The $source stage will project the timestamp for a document into this field."
                type: string
                optional: true
            tsFieldName:
                description: "The $source stage will project the timestamp for a document into this field."
                type: string
                optional: true
            streamMetaFieldName:
                description: "The field name that the stream metadata is projected to. If set to empty, the stream metadata will not be projected into the documents."
                type: string
                default: '"_stream_meta"'
            partitionIdleTimeout:
                description: "The amount of time that a partition is allowed to be idle before sending an idle watermark message."
                type: StreamTimeDuration
                optional: true
            testOnlyPartitionCount:
                description: "The number of topic partitions to use for the test."
                type:
                    variant: [int, array<int>]
                optional: true
            config:
                description: "Additional configuration options for the Kafka $source."
                type: KafkaSourceConfigOptions
                optional: true

    ChangeStreamConfigOptions:
        description: "Optional configuration options for a change stream $source."
        strict: true
        fields:
            startAfter:
                cpp_name: startAfter
                type: resumeToken
                optional: true
                description: An object representing the point after which we should start reporting
                             changes from. This is allowed to be a token from an invalidating
                             command. Only one of startAfter or startAtOperationTime
                             should be specified.
            startAtOperationTime:
                cpp_name: startAtOperationTime
                type:
                    variant: [timestamp, date]
                optional: true
                description: The operation time after which we should start reporting changes.
                             Only one of startAfter or startAtOperationTime should
                             be specified.
            fullDocument:
                cpp_name: fullDocument
                type: FullDocumentMode
                optional: true
                description:  A string '"updateLookup"', '"default"', '"whenAvailable"', or
                             '"required"', indicating whether return a full document or just
                             changes for an update.
            fullDocumentOnly:
                description: If set and is true, the $source return the value of fullDocument of
                             the change stream. The fullDocument parameter must be set to
                             updateLookup or required
                type: bool
                optional: true
            fullDocumentBeforeChange:
                description: Valid values are "off", "whenAvailable", or "required". If set to
                             "off", the "fullDocumentBeforeChange" field of the output document
                             is always omitted. If set to "whenAvailable", the
                             "fullDocumentBeforeChange" field will be populated with the
                             pre-image of the document modified by the current change event if
                             such a pre-image is available, and will be omitted otherwise. If
                             set to "required", then the "fullDocumentBeforeChange" field is
                             always populated and an exception is thrown if the pre-image is not
                             available.
                type: FullDocumentBeforeChangeMode
                optional: true
            pipeline:
                description: "Pipeline to process the change stream documents."
                type: array<object>
                optional: true

    ChangeStreamSourceOptions:
        description: "$source stage options for a change stream"
        strict: true
        fields:
            connectionName:
                description: "Name of the change streams source, should be the same as the Connection.name."
                type: string
            timeField:
                description: "Expression for computing the event time on a Document."
                type: 
                    variant: [object, string]
                optional: true
            tsFieldOverride:
                # TODO(SERVER-88461): Remove this here and elsewhere once the doc changes are out.
                description: "The $source stage will project the timestamp for a document into this field."
                type: string
                optional: true
            tsFieldName:
                description: "The $source stage will project the timestamp for a document into this field."
                type: string
                optional: true
            streamMetaFieldName:
                description: "The field name that the stream metadata is projected to. If set to empty, the stream metadata will not be projected into the documents."
                type: string
                default: '"_stream_meta"'
            db:
                description: "The database changestream to read."
                type: string
                optional: true
            coll:
                description: "The collection or group of collections we are interested in."
                type: 
                    variant: [string, array<string>]
                optional: true
            config:
                description: "Additional configuration options for the change stream $source."
                type: ChangeStreamConfigOptions
                optional: true

    TumblingWindowOptions:
        description: "$tumblingWindow stage options"
        strict: true
        fields:
            boundary:
                description: "String representing how window boundaries are determined."
                type: WindowBoundary
                default: eventTime
            interval:
                description: "Defines the size of the window."
                type: StreamTimeDuration
            pipeline:
                description: "The inner pipeline of the window."
                type: pipeline
            offset:
                description: "Defines the offset of the window from the UTC."
                type: TimeOffset
                optional: true
            idleTimeout:
                description: "If set, open windows are closed if the $source is idle for this duration plus the window size."
                type: 
                    variant: [StreamTimeDuration, int]
                optional: true
            allowedLateness:
                description: "Defines the allowed lateness for documents."
                type: 
                    variant: [StreamTimeDuration, int]
                optional: true

    HoppingWindowOptions:
        description: "$hoppingWindow stage options"
        strict: true
        fields:
            boundary:
                description: "String representing how window boundaries are determined. Should be one of 'eventTime' and 'processingTime'."
                type: WindowBoundary
                default: eventTime
            interval:
                description: "Defines the size of the window."
                type: StreamTimeDuration
            hopSize:
                description: "Defines the size between windows."
                type: StreamTimeDuration
            pipeline:
                description: "The inner pipeline of the window."
                type: pipeline
            offset:
                description: "Defines the offset of the window from the UTC."
                type: TimeOffset
                optional: true
            idleTimeout:
                description: "If set, open windows are closed if the $source is idle for this duration plus the window size."
                type: 
                    variant: [StreamTimeDuration, int]
                optional: true
            allowedLateness:
                description: "Defines the allowed lateness for documents."
                type: 
                    variant: [StreamTimeDuration, int]
                optional: true

    SessionWindowOptions:
        description: "$sessionWindow stage options"
        strict: true
        fields:
            gap:
                description: "Defines the gap between sessions."
                type: StreamTimeDuration
            pipeline:
                description: "The inner pipeline of the window."
                type: pipeline
            partitionBy:
                description: "Expression for the partition."
                type:
                    variant: [object, string]
                optional: true
            allowedLateness:
                description: "Defines the allowed lateness for documents."
                type: 
                    variant: [StreamTimeDuration, int]
                optional: true


    ValidateOptions:
        description: "$validate stage options"
        strict: true
        fields:
            validator:
                description: "validation expression"
                type: object
            validationAction:
                description: "validation action"
                type: StreamsValidationAction
                default: Discard

    AtlasCollection:
        description: Specifies details about Atlas instance and collection.
                     Currently used by $merge and $lookup stages.
        strict: true
        fields:
            connectionName:
                type: string
                description: Name of the connection to use from the connections list.
            db:
                type: nameExpression
                description: The literal or dynamic database name.
            coll:
                type: nameExpression
                description: The literal or dynamic collection name.

    MergeOperatorSpec:
        description: Specifies the $merge stage of a stream processing pipeline.
        strict: true
        fields:
            into:
                type: object
                description: Target MongoDB instance to merge documents into.

            "on":
                type: MergeOnFields
                optional: true
                description: A single field or array of fields that uniquely identify a document.

            let:
                type: object
                optional: true
                description: Specifies variables to use in the update pipeline defined in
                             MergeWhenMatchedPolicy when the 'whenMatched' mode is a custom
                             pipeline.

            whenMatched:
                type: MergeWhenMatchedPolicy
                optional: true
                description: The merge mode for the merge operation when source and target elements
                             match.

            whenNotMatched:
                type: MergeWhenNotMatchedMode
                optional: true
                description: The merge mode for the merge operation when source and target elements
                             do not match.

    KafkaSinkOptions:
        description: "Specifies details about an $emit stage configured to output to a Kafka topic"
        strict: true
        fields:
            connectionName:
                type: string
                description: Name of the connection to use from the connections list.
            topic:
                description: "Topic name to use for the sink data."
                type: nameExpression
            config:
                description: "Kafka sink configuration."
                type: KafkaSinkConfigOptions
                optional: true
            testOnlyPartition:
                description: "Specifies a single partition to write all output to."
                type: int
                optional: true
    
    TimeseriesSinkOptions:
        description: Specifies the options for sink operator $emit to Time Series collection.
        strict: true
        fields:
            connectionName:
                type: string
                description: Name of the connection to use from the connections list.
            db:
                type:
                    variant: [object, string]
                description: The string or expression representing database name
            coll:
                type:
                    variant: [object, string]
                description: The string or expression representing collection name
            timeseries:
                type: TimeseriesOptions
                description: Sepcifies the details of the target Time Series collection
                optional: true 

    HttpsConfigOptions:
        description: "Optional configuration options for the $https operator"
        strict: true
        fields:
            connectionTimeoutSec:
                description: "The timeout (in seconds) for establishing a HTTP connection."
                type: int
                default: 30
                validator:
                    gt: 0
                    lt: 900
            requestTimeoutSec:
                description: "The timeout (in seconds) for making a request."
                type: int
                default: 60
                validator:
                    gt: 0
                    lt: 900

    HttpsOptions:
        description: "$https stage options."
        strict: true
        fields:
            connectionName:
                description: "Name of the https source."
                type: string
            path:
                description: "The path to append onto the https connection's url."
                type:
                    variant: [object, string]
                optional: true
            parameters:
                description: "Query parameters used when making a request to the https."
                type: object
                optional: true
            method:
                description: "The HTTP verb used when making a request to the https."
                type: HttpMethod
                default: MethodGet
            headers:
                description: "The headers to send to the https. Can be an expression and will be evaluated against each input document."
                type: object
                optional: true
            as:
                description: "Defines the field name for REST API responses."
                type: string
            onError:
                description: "Describes how error responses from the https connection are handled"
                type: OnError
                default: DLQ
            payload:
                description: "An inner pipeline that determines the payload sent for the request, otherwise the incoming document will be sent. Only supported with POST, PUT, and PATCH"
                type: pipeline
                optional: true
            config:
                description: "Additional configuration options for the $https operator"
                type: HttpsConfigOptions
                optional: true
