#
#    Copyright (C) 2023-present MongoDB, Inc.
#

global:
    cpp_namespace: "mongo"
    cpp_includes:
        - "mongo/db/pipeline/aggregation_request_helper.h"
        - "mongo/db/pipeline/name_expression.h"

imports:
    - "mongo/db/basic_types.idl"
    - "mongo/db/pipeline/document_source_merge.idl"
    - "mongo/db/pipeline/document_source_change_stream.idl"
    - "mongo/db/pipeline/name_expression.idl"

types:
    pipeline:
        bson_serialization_type: any
        description: "An array of objects specifying the window's inner pipeline."
        cpp_type: "std::vector<mongo::BSONObj>"
        deserializer: ::mongo::parsePipelineFromBSON

enums:
    ConnectionType:
        description: "Connection type"
        type: string
        values:
            Kafka: "kafka"
            Atlas: "atlas"
            SampleSolar: "sample_solar"
            InMemory: "in_memory"

    StreamsValidationAction:
        description: "validation action for $validate stage"
        type: string
        values:
            Discard: "discard"
            Dlq: "dlq"

    StreamTimeUnit:
        description: "Units of time for streaming pipeline stages."
        type: string
        values:
            Millisecond: "ms"
            Second: "second"
            Minute: "minute"
            Hour: "hour"
            Day: "day"

    KafkaSourceStartAt:
        description: "Start position options for Kafka."
        type: string
        values:
            Earliest: "earliest"
            Latest: "latest"

    KafkaAuthSaslMechanism:
        type: string
        description: "Kafka sasl.mechanism options."
        values:
            Plain: "PLAIN"
            ScramSHA256: "SCRAM-SHA-256"
            ScramSHA512: "SCRAM-SHA-512"

    KafkaAuthSecurityProtocol:
        type: string
        description: "Kafka security.protocol options."
        values:
            Plaintext: "PLAINTEXT"
            SaslPlaintext: "SASL_PLAINTEXT"
            SaslSSL: "SASL_SSL"

structs:
    StreamTimeDuration:
        description: "A duration of time."
        strict: true
        fields:
            size:
                description: "The size of the duration in terms of unit."
                type: int
                validator: {gte: 0}
            unit:
                description: "The time unit used for the duration."
                type: StreamTimeUnit

    TimeOffset:
        description: "A time offset from the UTC."
        strict: true
        fields:
            offsetFromUtc:
                description: "The offset from the UTC in terms of unit."
                type: int
            unit:
                description: "The time unit used for the offset."
                type: StreamTimeUnit

    KafkaAuthOptions:
        description: "Auth related options for a Kafka connection."
        strict: true
        fields:
            saslMechanism:
                description: "sasl.mechanism Kafka config."
                type: KafkaAuthSaslMechanism
                optional: true
            saslUsername:
                description: "sasl.username Kafka config."
                type: string
                optional: true
            saslPassword:
                description: "sasl.password Kafka config."
                type: string
                optional: true
            securityProtocol:
                description: "security.protocol Kafka config."
                type: KafkaAuthSecurityProtocol
                optional: true

    KafkaConnectionOptions:
        description: "Kafka connection options."
        strict: true
        fields:
            bootstrapServers:
                description: "Comma separate string of bootstrapServer network locations."
                type: string
            isTestKafka:
                description: "If set and true, use a mock Kafka connection."
                type: bool
                optional: true
            auth:
                description: "Kafka config values related to auth, like sasl.username."
                type: KafkaAuthOptions
                optional: true

    AtlasConnectionOptions:
        description: "Atlas connection options."
        strict: true
        fields:
            uri:
                description: "Atlas connection URI"
                type: string
            pemFile:
                description: "Path to PEM file for authentication to an Atlas cluster."
                type: string
                optional: true
            caFile:
                description: "Path to CA file for verifying the PEM file above."
                type: string
                optional: true

    Connection:
        description: "Connection registry information."
        strict: true
        fields:
            name:
                description: "Name of this connection."
                type: string
            type:
                description: "Type of this connection e.g. kafka, atlas"
                type: ConnectionType
            options:
                description: "Options specific to the connectionType."
                type: object

    GeneratedDataSourceOptions:
        description: "$source stage options for a generated data source, in-memory or sample data"
        strict: true
        fields:
            connectionName:
                description: "Name of the data source, should be the same as the Connection.name."
                type: string
            timeField:
                description: "Expression for computing the event time on a Document."
                type: object
                optional: true
            tsFieldOverride:
                description: "The $source stage will project the timestamp for a document into this field."
                type: string
                optional: true
            allowedLateness:
                description: "The allowed lateness for documents in a window."
                type: StreamTimeDuration
                optional: true

    KafkaSourceConfigOptions:
        description: "Optional configuration options for a Kafka $source."
        strict: true
        fields:
            startAt:
                description: "latest will start the $source at the latest event in the topic. earliest will start the source at the earliest event."
                type: KafkaSourceStartAt
                default: Latest

    KafkaSourceOptions:
        description: "$source stage options for Kafka sources."
        strict: true
        fields:
            connectionName:
                description: "Name of the Kafka source, should be the same as the Connection.name."
                type: string
            topic:
                description: "Topic name to use for the source data."
                type: string
            timeField:
                description: "Expression for computing the event time on a Document."
                type: object
                optional: true
            tsFieldOverride:
                description: "The $source stage will project the timestamp for a document into this field."
                type: string
                optional: true
            allowedLateness:
                description: "The allowed lateness for documents in a window."
                type: StreamTimeDuration
                optional: true
            idlenessTimeout:
                description: "The amount of time that a partition is allowed to be idle before sending an idle watermark message."
                type: StreamTimeDuration
                optional: true
            testOnlyPartitionCount:
                description: "The number of topic partitions to use for the test."
                type: int
                validator: {gte: 1}
                optional: true
            config:
                description: "Additional configuration options for the Kafka $source."
                type: KafkaSourceConfigOptions
                optional: true

    ChangeStreamSourceOptions:
        description: "$source stage options for a change stream"
        strict: true
        fields:
            connectionName:
                description: "Name of the change streams source, should be the same as the Connection.name."
                type: string
            timeField:
                description: "Expression for computing the event time on a Document."
                type: object
                optional: true
            tsFieldOverride:
                description: "The $source stage will project the timestamp for a document into this field."
                type: string
                optional: true
            allowedLateness:
                description: "The allowed lateness for documents in a window."
                type: StreamTimeDuration
                optional: true
            db:
                description: "The database to connect to."
                type: string
            coll:
                description: "The collection to connect to."
                type: string
                optional: true
            startAfter:
                cpp_name: startAfter
                type: resumeToken
                optional: true
                description: An object representing the point after which we should start reporting
                             changes from. This is allowed to be a token from an invalidating
                             command. Only one of startAfter or startAtOperationTime
                             should be specified.
            startAtOperationTime:
                cpp_name: startAtOperationTime
                type: timestamp
                optional: true
                description: The operation time after which we should start reporting changes.
                             Only one of startAfter or startAtOperationTime should
                             be specified.
            fullDocument:
                cpp_name: fullDocument
                type: FullDocumentMode
                optional: true
                description:  A string '"updateLookup"', '"default"', '"whenAvailable"', or
                             '"required"', indicating whether return a full document or just
                             changes for an update.

    TumblingWindowOptions:
        description: "$tumblingWindow stage options"
        strict: true
        fields:
            interval:
                description: "Defines the size of the window."
                type: StreamTimeDuration
            pipeline:
                description: "The inner pipeline of the window."
                type: pipeline
            offset:
                description: "Defines the offset of the window from the UTC."
                type: TimeOffset
                optional: true

    HoppingWindowOptions:
        description: "$hoppingWindow stage options"
        strict: true
        fields:
            interval:
                description: "Defines the size of the window."
                type: StreamTimeDuration
            hopSize:
                description: "Defines the size between windows."
                type: StreamTimeDuration
            pipeline:
                description: "The inner pipeline of the window."
                type: pipeline

    ValidateOptions:
        description: "$validate stage options"
        strict: true
        fields:
            validator:
                description: "validation expression"
                type: object
            validationAction:
                description: "validation action"
                type: StreamsValidationAction
                default: Discard

    AtlasCollection:
        description: Specifies details about Atlas instance and collection.
                     Currently used by $merge and $lookup stages.
        strict: true
        fields:
            connectionName:
                type: string
                description: Name of the connection to use from the connections list.
            db:
                type: nameExpression
                description: The literal or dynamic database name.
            coll:
                type: nameExpression
                description: The literal or dynamic collection name.

    MergeOperatorSpec:
        description: Specifies the $merge stage of a stream processing pipeline.
        strict: true
        fields:
            into:
                type: object
                description: Target MongoDB instance to merge documents into.

            on:
                type: MergeOnFields
                optional: true
                description: A single field or array of fields that uniquely identify a document.

            whenMatched:
                type: MergeWhenMatchedMode
                optional: true
                description: The merge mode for the merge operation when source and target elements
                             match.

            whenNotMatched:
                type: MergeWhenNotMatchedMode
                optional: true
                description: The merge mode for the merge operation when source and target elements
                             do not match.

    KafkaSinkOptions:
        description: "Specifies details about an $emit stage configured to output to a Kafka topic"
        strict: true
        fields:
            connectionName:
                type: string
                description: Name of the connection to use from the connections list.
            topic:
                description: "Topic name to use for the sink data."
                type: nameExpression
