#
#    Copyright (C) 2023-present MongoDB, Inc.
#

global:
    cpp_namespace: "mongo"
    cpp_includes:
        - "mongo/db/pipeline/aggregation_request_helper.h"

imports:
    - "mongo/db/basic_types.idl"
    - "mongo/db/modules/enterprise/src/streams/exec/common_types.idl"

types:
    pipeline:
        bson_serialization_type: any
        description: "An array of objects specifying the window's inner pipeline."
        cpp_type: "std::vector<mongo::BSONObj>"
        deserializer: ::mongo::parsePipelineFromBSON

structs:
    TumblingWindow:
        description: "$tumblingWindow stage"
        strict: true
        fields:
            interval:
                description: "Defines the size of the window."
                type: StreamTimeDuration
            pipeline:
                description: "The inner pipeline of the window."
                type: pipeline