# -*- mode: python -*-

Import("env")

env = env.Clone()

env.CppUnitTest(
    target="stream_manager_test",
    source=[],
)

env.CppUnitTest(
    target="container_stats_utils_test",
    source=[],
)

env.CppUnitTest(
    target="container_stats_test",
    source=[],
)
