# -*- mode: python -*-

Import('env')

env = env.Clone()

env.Library(
    target='kerberos_tool_options',
    source=[
        "kerberos_tool_options.cpp",
        env.Idlc('kerberos_tool_options.idl')[0],
    ],
    LIBDEPS_PRIVATE=[
        "$BUILD_DIR/mongo/base",
        "$BUILD_DIR/mongo/util/options_parser/options_parser_init",
    ]
)
