# -*- mode: python -*-


Import("env")

env = env.Clone()

env.BazelProgram(
    target="mongokerberos",
    source=[],
    AIB_COMPONENT="mongokerberos",
    AIB_COMPONENTS_EXTRA=[
        "dist",
        "dist-test",
        "tools",
    ],
)
