# Copyright (C) 2021-present MongoDB, Inc. and subject to applicable commercial license.

global:
  cpp_namespace: "mongo"
  cpp_includes:
    - "mongo/config.h"
    - "mongo/util/net/ssl_options.h"
  configs:
    section: "TLS Options"
    source: [ yaml, cli, ini ]
    # Name these initializers so they can be invoked from fips_options_test.cpp
    initializer: FIPSOptionsIDL

imports:
  - "mongo/db/basic_types.idl"

configs:
  "net.tls.FIPSMode":
    description: "Activate FIPS 140-2 mode at startup"
    short_name: tlsFIPSMode
    deprecated_name: "net.ssl.FIPSMode"
    deprecated_short_name: sslFIPSMode
    arg_vartype: Switch
    cpp_varname: sslGlobalParams.sslFIPSMode