# Copyright (C) 2020-present MongoDB, Inc. and subject to applicable commercial license.

global:
  cpp_namespace: "mongo"

imports:
  - "mongo/db/basic_types.idl"

structs:
  CollectionProperties:
    description: "A document representing the metadata of the collection being exported"
    strict: false
    fields:
      ns:
        description: "Namespace of the collection"
        type: namespacestring
      metadata:
        description: "Catalog entry corresponding to the collection"
        type: object
      numRecords:
        description: "Number of records in the collection"
        type: long
      dataSize:
        description: "Date size of the collection"
        type: long
      collectionFile:
        description: "Path to the collection file"
        type: string
      indexFiles:
        description: "Document representing paths to index files"
        type: object
      storageMetadata:
        description: "Contains the storage engines file and table metadata for each ident"
        type: object
      directoryPerDB:
        description: "Whether the exporting node was running with the directoryPerDB option"
        type: bool
      directoryForIndexes:
        description: "Whether the exporting node was running with the directoryForIndexes option"
        type: bool
