# Copyright (C) 2020-present MongoDB, Inc.  All Rights Reserved.

global:
  cpp_namespace: "mongo::feature_flags"

feature_flags:
  # TODO (SERVER-52605): Remove featureFlagLiveImportExport.
  featureFlagLiveImportExport:
    description: "When enabled, allow live import/export of collection files"
    cpp_varname: gLiveImportExport
    default: true
    version: 4.9
