# -*- mode: python -*-

Import("env")
Import("wiredtiger")

env = env.Clone()

if not wiredtiger:
    env.FatalError("Live import/export requires WiredTiger")

wtEnv = env.Clone()
wtEnv.InjectThirdParty(libraries=["wiredtiger"])

env.SConscript(
    must_exist=1,
    dirs=[
        "commands",
    ],
    exports=[
        "env",
    ],
)
