# -*- python -*-

Import("env")
Import("wiredtiger")

env = env.Clone()

if not wiredtiger:
    env.FatalError("The InMemory storage engine requires WiredTiger")

wtEnv = env.Clone()
wtEnv.InjectThirdParty(libraries=["wiredtiger"])
