#-*- python -*-

Import("env")
Import("wiredtiger")

env = env.Clone()

if not wiredtiger:
    env.FatalError("The InMemory storage engine requires WiredTiger")

wtEnv = env.Clone()
wtEnv.InjectThirdParty(libraries=['wiredtiger'])
wtEnv.Library(
    target='storage_inmemory',
    source=[
        'inmemory_global_options.cpp',
        'inmemory_init.cpp',
        'inmemory_options_init.cpp',
        wtEnv.Idlc('inmemory_global_options.idl')[0],
    ],
    PROGDEPS_DEPENDENTS=[
        '$BUILD_DIR/mongo/dbtests/dbtest',
        '$BUILD_DIR/mongo/mongod'
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/storage/wiredtiger/storage_wiredtiger',
        '$BUILD_DIR/mongo/db/storage/wiredtiger/storage_wiredtiger_core',
        '$BUILD_DIR/mongo/db/storage/kv/kv_engine',
        '$BUILD_DIR/mongo/db/storage/storage_engine_lock_file',
        '$BUILD_DIR/mongo/db/storage/storage_engine_metadata',
    ],
    LIBDEPS_PRIVATE=[
        '$BUILD_DIR/mongo/db/server_options_core',
        '$BUILD_DIR/mongo/db/storage/storage_engine_common',
        '$BUILD_DIR/mongo/util/options_parser/options_parser'
    ],
)
