Import('env')

env = env.Clone()

env.Library(
    target='blockstore',
    source=[
        'blockstore_http.cpp',
        'list_dir.cpp',
        'reader.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/bson/util/bson_extract',
    ],
    LIBDEPS_PRIVATE=[
        '$BUILD_DIR/mongo/util/net/http_client',
    ],
)

env.CppIntegrationTest(
    target='list_dir_test',
    source=[
        'list_dir_test.cpp',
    ],
    LIBDEPS=[
        'blockstore',
    ],
)

env.CppIntegrationTest(
    target='reader_test',
    source=[
        'reader_test.cpp',
    ],
    LIBDEPS=[
        'blockstore',
    ],
)
