# -*- mode: python -*-

Import("env")

env = env.Clone()

env.BazelProgram(
    target="streams_pipeline_runner_main",
    source=[],
)

env.BazelProgram(
    target="streams_merge_operator_main",
    source=[],
)
