# -*- mode: python -*-

Import('env')

env = env.Clone()

env.InjectThirdParty(libraries=['librdkafka'])

env.Program(
    target='streams_pipeline_runner_main',
    source=[
        'pipeline_runner_main.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/db/auth/authmocks',
        '$BUILD_DIR/mongo/db/query/query_test_service_context',
        '../exec/streams_parser',
    ],
)
