# -*- mode: python -*-

Import("env")

env.CppUnitTest(
    target="file_copy_based_initial_syncer_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="initial_sync_file_mover_test",
    source=[],
    LIBDEPS=[],
)
