# -*- mode: python -*-

Import("env")
Import("wiredtiger")

if not wiredtiger:
    env.FatalError("fcbis requires WiredTiger")

env = env.Clone()
env.InjectThirdParty(libraries=["wiredtiger"])

env.Library(
    target="file_copy_based_initial_syncer",
    source=[
        "file_copy_based_initial_syncer.cpp",
        "initial_sync_file_mover.cpp",
        "backup_file_cloner.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/base",
        "$BUILD_DIR/mongo/db/catalog/catalog_control",
        "$BUILD_DIR/mongo/db/modules/enterprise/src/hot_backups/hot_backups",
        "$BUILD_DIR/mongo/db/repl/initial_syncer",
        "$BUILD_DIR/mongo/db/service_context",
        "$BUILD_DIR/mongo/db/startup_recovery",
        "$BUILD_DIR/mongo/db/storage/storage_engine_common",
        "$BUILD_DIR/mongo/db/storage/wiredtiger/storage_wiredtiger_core",
        "$BUILD_DIR/mongo/watchdog/watchdog",
    ],
    LIBDEPS_PRIVATE=[
        "$BUILD_DIR/mongo/db/concurrency/exception_util",
        "$BUILD_DIR/mongo/db/cursor_server_params",
        "$BUILD_DIR/mongo/db/dbhelpers",
        "$BUILD_DIR/mongo/db/index_builds_coordinator_interface",
        "$BUILD_DIR/mongo/db/repl/repl_server_parameters",
        "$BUILD_DIR/mongo/db/repl/replication_auth",
        "$BUILD_DIR/mongo/db/serverless/serverless_lock",
        "$BUILD_DIR/mongo/db/storage/storage_file_util",
        "$BUILD_DIR/mongo/db/storage/storage_options",
        "$BUILD_DIR/mongo/db/transaction/transaction",
        "$BUILD_DIR/mongo/executor/scoped_task_executor",
        "$BUILD_DIR/mongo/util/progress_meter",
    ],
    LIBDEPS_DEPENDENTS=[
        "$BUILD_DIR/mongo/db/mongod_initializers",
    ],
    LIBDEPS_TAGS=[
        "lint-allow-nonprivate-on-deps-dependents",
        "lint-allow-bidirectional-edges",
    ],
)

env.CppUnitTest(
    target="file_copy_based_initial_syncer_test",
    source=[
        "backup_file_cloner_test.cpp",
        "file_copy_based_initial_syncer_test.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/base",
        "$BUILD_DIR/mongo/db/auth/authmocks",
        "$BUILD_DIR/mongo/db/index_builds_coordinator_mongod",
        "$BUILD_DIR/mongo/db/modules/enterprise/src/hot_backups/backup_cqf_utils",
        "$BUILD_DIR/mongo/db/repl/cloner_test_fixtures",
        "$BUILD_DIR/mongo/db/repl/data_replicator_external_state_mock",
        "$BUILD_DIR/mongo/db/repl/repl_server_parameters",
        "$BUILD_DIR/mongo/db/repl/replmocks",
        "$BUILD_DIR/mongo/db/repl/sync_source_selector_mock",
        "$BUILD_DIR/mongo/db/repl/task_executor_mock",
        "$BUILD_DIR/mongo/db/service_context_d_test_fixture",
        "$BUILD_DIR/mongo/db/storage/backup_block",
        "$BUILD_DIR/mongo/db/storage/backup_cursor_hooks",
        "$BUILD_DIR/mongo/db/storage/devnull/storage_devnull_core",
        "$BUILD_DIR/mongo/db/storage/storage_options",
        "$BUILD_DIR/mongo/dbtests/mocklib",
        "$BUILD_DIR/mongo/executor/thread_pool_task_executor_test_fixture",
        "$BUILD_DIR/mongo/watchdog/watchdog_mock",
        "file_copy_based_initial_syncer",
    ],
)

env.CppUnitTest(
    target="initial_sync_file_mover_test",
    source=[
        "initial_sync_file_mover_test.cpp",
    ],
    LIBDEPS=[
        "file_copy_based_initial_syncer",
    ],
)
