version: 1.0.0
filters:
  - "*chunk_migration_command*":
    approvers:
      - 10gen/server-cluster-scalability
  - "*transition_from_dedicated*":
    approvers:
      - 10gen/server-cluster-scalability
  - "*transition_to_dedicated*":
    approvers:
      - 10gen/server-cluster-scalability
